In [1]:
import pandas as pd

In [2]:
rmf=pd.read_csv(r'C:\Users\DELL3521\Desktop\cs.csv')
rmf

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,12/1/2010 8:26,7.65,17850.0,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,12/1/2010 8:26,4.25,17850.0,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,12/1/2010 8:28,1.85,17850.0,United Kingdom
8,536366,22632,HAND WARMER RED POLKA DOT,6,12/1/2010 8:28,1.85,17850.0,United Kingdom
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,12/1/2010 8:34,1.69,13047.0,United Kingdom
10,536367,22745,POPPY'S PLAYHOUSE BEDROOM,6,12/1/2010 8:34,2.10,13047.0,United Kingdom
11,536367,22748,POPPY'S PLAYHOUSE KITCHEN,6,12/1/2010 8:34,2.10,13047.0,United Kingdom
12,536367,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,8,12/1/2010 8:34,3.75,13047.0,United Kingdom
13,536367,22310,IVORY KNITTED MUG COSY,6,12/1/2010 8:34,1.65,13047.0,United Kingdom
14,536367,84969,BOX OF 6 ASSORTED COLOUR TEASPOONS,6,12/1/2010 8:34,4.25,13047.0,United Kingdom
15,536367,22623,BOX OF VINTAGE JIGSAW BLOCKS,3,12/1/2010 8:34,4.95,13047.0,United Kingdom
16,536367,22622,BOX OF VINTAGE ALPHABET BLOCKS,2,12/1/2010 8:34,9.95,13047.0,United Kingdom
17,536367,21754,HOME BUILDING BLOCK WORD,3,12/1/2010 8:34,5.95,13047.0,United Kingdom
18,536367,21755,LOVE BUILDING BLOCK WORD,3,12/1/2010 8:34,5.95,13047.0,United Kingdom
19,536367,21777,RECIPE BOX WITH METAL HEART,4,12/1/2010 8:34,7.95,13047.0,United Kingdom
20,536367,48187,DOORMAT NEW ENGLAND,4,12/1/2010 8:34,7.95,13047.0,United Kingdom
21,536368,22960,JAM MAKING SET WITH JARS,6,12/1/2010 8:34,4.25,13047.0,United Kingdom
22,536368,22913,RED COAT RACK PARIS FASHION,3,12/1/2010 8:34,4.95,13047.0,United Kingdom
23,536368,22912,YELLOW COAT RACK PARIS FASHION,3,12/1/2010 8:34,4.95,13047.0,United Kingdom
24,536368,22914,BLUE COAT RACK PARIS FASHION,3,12/1/2010 8:34,4.95,13047.0,United Kingdom
25,536369,21756,BATH BUILDING BLOCK WORD,3,12/1/2010 8:35,5.95,13047.0,United Kingdom
26,536370,22728,ALARM CLOCK BAKELIKE PINK,24,12/1/2010 8:45,3.75,12583.0,France
27,536370,22727,ALARM CLOCK BAKELIKE RED,24,12/1/2010 8:45,3.75,12583.0,France
28,536370,22726,ALARM CLOCK BAKELIKE GREEN,12,12/1/2010 8:45,3.75,12583.0,France
29,536370,21724,PANDA AND BUNNIES STICKER SHEET,12,12/1/2010 8:45,0.85,12583.0,France
...,...,...,...,...,...,...,...,...
541879,581585,22726,ALARM CLOCK BAKELIKE GREEN,8,12/9/2011 12:31,3.75,15804.0,United Kingdom
541880,581585,22727,ALARM CLOCK BAKELIKE RED,4,12/9/2011 12:31,3.75,15804.0,United Kingdom
541881,581585,16016,LARGE CHINESE STYLE SCISSOR,10,12/9/2011 12:31,0.85,15804.0,United Kingdom
541882,581585,21916,SET 12 RETRO WHITE CHALK STICKS,24,12/9/2011 12:31,0.42,15804.0,United Kingdom
541883,581585,84692,BOX OF 24 COCKTAIL PARASOLS,25,12/9/2011 12:31,0.42,15804.0,United Kingdom
541884,581585,84946,ANTIQUE SILVER T-LIGHT GLASS,12,12/9/2011 12:31,1.25,15804.0,United Kingdom
541885,581585,21684,SMALL MEDINA STAMPED METAL BOWL,12,12/9/2011 12:31,0.85,15804.0,United Kingdom
541886,581585,22398,MAGNETS PACK OF 4 SWALLOWS,12,12/9/2011 12:31,0.39,15804.0,United Kingdom
541887,581585,23328,SET 6 SCHOOL MILK BOTTLES IN CRATE,4,12/9/2011 12:31,3.75,15804.0,United Kingdom
541888,581585,23145,ZINC T-LIGHT HOLDER STAR LARGE,12,12/9/2011 12:31,0.95,15804.0,United Kingdom
541889,581585,22466,FAIRY TALE COTTAGE NIGHT LIGHT,12,12/9/2011 12:31,1.95,15804.0,United Kingdom
541890,581586,22061,LARGE CAKE STAND HANGING STRAWBERY,8,12/9/2011 12:49,2.95,13113.0,United Kingdom
541891,581586,23275,SET OF 3 HANGING OWLS OLLIE BEAK,24,12/9/2011 12:49,1.25,13113.0,United Kingdom
541892,581586,21217,RED RETROSPOT ROUND CAKE TINS,24,12/9/2011 12:49,8.95,13113.0,United Kingdom
541893,581586,20685,DOORMAT RED RETROSPOT,10,12/9/2011 12:49,7.08,13113.0,United Kingdom
541894,581587,22631,CIRCUS PARADE LUNCH BOX,12,12/9/2011 12:50,1.95,12680.0,France
541895,581587,22556,PLASTERS IN TIN CIRCUS PARADE,12,12/9/2011 12:50,1.65,12680.0,France
541896,581587,22555,PLASTERS IN TIN STRONGMAN,12,12/9/2011 12:50,1.65,12680.0,France
541897,581587,22728,ALARM CLOCK BAKELIKE PINK,4,12/9/2011 12:50,3.75,12680.0,France
541898,581587,22727,ALARM CLOCK BAKELIKE RED,4,12/9/2011 12:50,3.75,12680.0,France
541899,581587,22726,ALARM CLOCK BAKELIKE GREEN,4,12/9/2011 12:50,3.75,12680.0,France
541900,581587,22730,ALARM CLOCK BAKELIKE IVORY,4,12/9/2011 12:50,3.75,12680.0,France
541901,581587,22367,CHILDRENS APRON SPACEBOY DESIGN,8,12/9/2011 12:50,1.95,12680.0,France
541902,581587,22629,SPACEBOY LUNCH BOX,12,12/9/2011 12:50,1.95,12680.0,France
541903,581587,23256,CHILDRENS CUTLERY SPACEBOY,4,12/9/2011 12:50,4.15,12680.0,France
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France

In [3]:
rmf['Country'].value_counts()

United Kingdom          495478
Germany                   9495
France                    8557
EIRE                      8196
Spain                     2533
Netherlands               2371
Belgium                   2069
Switzerland               2002
Portugal                  1519
Australia                 1259
Norway                    1086
Italy                      803
Channel Islands            758
Finland                    695
Cyprus                     622
Sweden                     462
Unspecified                446
Austria                    401
Denmark                    389
Japan                      358
Poland                     341
Israel                     297
USA                        291
Hong Kong                  288
Singapore                  229
Iceland                    182
Canada                     151
Greece                     146
Malta                      127
United Arab Emirates        68
European Community          61
RSA                         58
Lebanon                     45
Lithuania                   35
Brazil                      32
Czech Republic              30
Bahrain                     19
Saudi Arabia                10
Name: Country, dtype: int64

In [4]:
rmf['InvoiceDate'] =  pd.to_datetime(rmf['InvoiceDate'])

In [5]:
rmf.dtypes

InvoiceNo              object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice             float64
CustomerID            float64
Country                object
dtype: object

In [6]:
rmf

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,2010-12-01 08:26:00,7.65,17850.0,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,2010-12-01 08:26:00,4.25,17850.0,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom
8,536366,22632,HAND WARMER RED POLKA DOT,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,2010-12-01 08:34:00,1.69,13047.0,United Kingdom
10,536367,22745,POPPY'S PLAYHOUSE BEDROOM,6,2010-12-01 08:34:00,2.10,13047.0,United Kingdom
11,536367,22748,POPPY'S PLAYHOUSE KITCHEN,6,2010-12-01 08:34:00,2.10,13047.0,United Kingdom
12,536367,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,8,2010-12-01 08:34:00,3.75,13047.0,United Kingdom
13,536367,22310,IVORY KNITTED MUG COSY,6,2010-12-01 08:34:00,1.65,13047.0,United Kingdom
14,536367,84969,BOX OF 6 ASSORTED COLOUR TEASPOONS,6,2010-12-01 08:34:00,4.25,13047.0,United Kingdom
15,536367,22623,BOX OF VINTAGE JIGSAW BLOCKS,3,2010-12-01 08:34:00,4.95,13047.0,United Kingdom
16,536367,22622,BOX OF VINTAGE ALPHABET BLOCKS,2,2010-12-01 08:34:00,9.95,13047.0,United Kingdom
17,536367,21754,HOME BUILDING BLOCK WORD,3,2010-12-01 08:34:00,5.95,13047.0,United Kingdom
18,536367,21755,LOVE BUILDING BLOCK WORD,3,2010-12-01 08:34:00,5.95,13047.0,United Kingdom
19,536367,21777,RECIPE BOX WITH METAL HEART,4,2010-12-01 08:34:00,7.95,13047.0,United Kingdom
20,536367,48187,DOORMAT NEW ENGLAND,4,2010-12-01 08:34:00,7.95,13047.0,United Kingdom
21,536368,22960,JAM MAKING SET WITH JARS,6,2010-12-01 08:34:00,4.25,13047.0,United Kingdom
22,536368,22913,RED COAT RACK PARIS FASHION,3,2010-12-01 08:34:00,4.95,13047.0,United Kingdom
23,536368,22912,YELLOW COAT RACK PARIS FASHION,3,2010-12-01 08:34:00,4.95,13047.0,United Kingdom
24,536368,22914,BLUE COAT RACK PARIS FASHION,3,2010-12-01 08:34:00,4.95,13047.0,United Kingdom
25,536369,21756,BATH BUILDING BLOCK WORD,3,2010-12-01 08:35:00,5.95,13047.0,United Kingdom
26,536370,22728,ALARM CLOCK BAKELIKE PINK,24,2010-12-01 08:45:00,3.75,12583.0,France
27,536370,22727,ALARM CLOCK BAKELIKE RED,24,2010-12-01 08:45:00,3.75,12583.0,France
28,536370,22726,ALARM CLOCK BAKELIKE GREEN,12,2010-12-01 08:45:00,3.75,12583.0,France
29,536370,21724,PANDA AND BUNNIES STICKER SHEET,12,2010-12-01 08:45:00,0.85,12583.0,France
...,...,...,...,...,...,...,...,...
541879,581585,22726,ALARM CLOCK BAKELIKE GREEN,8,2011-12-09 12:31:00,3.75,15804.0,United Kingdom
541880,581585,22727,ALARM CLOCK BAKELIKE RED,4,2011-12-09 12:31:00,3.75,15804.0,United Kingdom
541881,581585,16016,LARGE CHINESE STYLE SCISSOR,10,2011-12-09 12:31:00,0.85,15804.0,United Kingdom
541882,581585,21916,SET 12 RETRO WHITE CHALK STICKS,24,2011-12-09 12:31:00,0.42,15804.0,United Kingdom
541883,581585,84692,BOX OF 24 COCKTAIL PARASOLS,25,2011-12-09 12:31:00,0.42,15804.0,United Kingdom
541884,581585,84946,ANTIQUE SILVER T-LIGHT GLASS,12,2011-12-09 12:31:00,1.25,15804.0,United Kingdom
541885,581585,21684,SMALL MEDINA STAMPED METAL BOWL,12,2011-12-09 12:31:00,0.85,15804.0,United Kingdom
541886,581585,22398,MAGNETS PACK OF 4 SWALLOWS,12,2011-12-09 12:31:00,0.39,15804.0,United Kingdom
541887,581585,23328,SET 6 SCHOOL MILK BOTTLES IN CRATE,4,2011-12-09 12:31:00,3.75,15804.0,United Kingdom
541888,581585,23145,ZINC T-LIGHT HOLDER STAR LARGE,12,2011-12-09 12:31:00,0.95,15804.0,United Kingdom
541889,581585,22466,FAIRY TALE COTTAGE NIGHT LIGHT,12,2011-12-09 12:31:00,1.95,15804.0,United Kingdom
541890,581586,22061,LARGE CAKE STAND HANGING STRAWBERY,8,2011-12-09 12:49:00,2.95,13113.0,United Kingdom
541891,581586,23275,SET OF 3 HANGING OWLS OLLIE BEAK,24,2011-12-09 12:49:00,1.25,13113.0,United Kingdom
541892,581586,21217,RED RETROSPOT ROUND CAKE TINS,24,2011-12-09 12:49:00,8.95,13113.0,United Kingdom
541893,581586,20685,DOORMAT RED RETROSPOT,10,2011-12-09 12:49:00,7.08,13113.0,United Kingdom
541894,581587,22631,CIRCUS PARADE LUNCH BOX,12,2011-12-09 12:50:00,1.95,12680.0,France
541895,581587,22556,PLASTERS IN TIN CIRCUS PARADE,12,2011-12-09 12:50:00,1.65,12680.0,France
541896,581587,22555,PLASTERS IN TIN STRONGMAN,12,2011-12-09 12:50:00,1.65,12680.0,France
541897,581587,22728,ALARM CLOCK BAKELIKE PINK,4,2011-12-09 12:50:00,3.75,12680.0,France
541898,581587,22727,ALARM CLOCK BAKELIKE RED,4,2011-12-09 12:50:00,3.75,12680.0,France
541899,581587,22726,ALARM CLOCK BAKELIKE GREEN,4,2011-12-09 12:50:00,3.75,12680.0,France
541900,581587,22730,ALARM CLOCK BAKELIKE IVORY,4,2011-12-09 12:50:00,3.75,12680.0,France
541901,581587,22367,CHILDRENS APRON SPACEBOY DESIGN,8,2011-12-09 12:50:00,1.95,12680.0,France
541902,581587,22629,SPACEBOY LUNCH BOX,12,2011-12-09 12:50:00,1.95,12680.0,France
541903,581587,23256,CHILDRENS CUTLERY SPACEBOY,4,2011-12-09 12:50:00,4.15,12680.0,France
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France

In [7]:
rmf['present date']='2011-12-10 12:50:00'

In [8]:
rmf

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,present date
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,2011-12-10 12:50:00
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,2011-12-10 12:50:00
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,2011-12-10 12:50:00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,2011-12-10 12:50:00
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,2011-12-10 12:50:00
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,2010-12-01 08:26:00,7.65,17850.0,United Kingdom,2011-12-10 12:50:00
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,2010-12-01 08:26:00,4.25,17850.0,United Kingdom,2011-12-10 12:50:00
7,536366,22633,HAND WARMER UNION JACK,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom,2011-12-10 12:50:00
8,536366,22632,HAND WARMER RED POLKA DOT,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom,2011-12-10 12:50:00
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,2010-12-01 08:34:00,1.69,13047.0,United Kingdom,2011-12-10 12:50:00
10,536367,22745,POPPY'S PLAYHOUSE BEDROOM,6,2010-12-01 08:34:00,2.10,13047.0,United Kingdom,2011-12-10 12:50:00
11,536367,22748,POPPY'S PLAYHOUSE KITCHEN,6,2010-12-01 08:34:00,2.10,13047.0,United Kingdom,2011-12-10 12:50:00
12,536367,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,8,2010-12-01 08:34:00,3.75,13047.0,United Kingdom,2011-12-10 12:50:00
13,536367,22310,IVORY KNITTED MUG COSY,6,2010-12-01 08:34:00,1.65,13047.0,United Kingdom,2011-12-10 12:50:00
14,536367,84969,BOX OF 6 ASSORTED COLOUR TEASPOONS,6,2010-12-01 08:34:00,4.25,13047.0,United Kingdom,2011-12-10 12:50:00
15,536367,22623,BOX OF VINTAGE JIGSAW BLOCKS,3,2010-12-01 08:34:00,4.95,13047.0,United Kingdom,2011-12-10 12:50:00
16,536367,22622,BOX OF VINTAGE ALPHABET BLOCKS,2,2010-12-01 08:34:00,9.95,13047.0,United Kingdom,2011-12-10 12:50:00
17,536367,21754,HOME BUILDING BLOCK WORD,3,2010-12-01 08:34:00,5.95,13047.0,United Kingdom,2011-12-10 12:50:00
18,536367,21755,LOVE BUILDING BLOCK WORD,3,2010-12-01 08:34:00,5.95,13047.0,United Kingdom,2011-12-10 12:50:00
19,536367,21777,RECIPE BOX WITH METAL HEART,4,2010-12-01 08:34:00,7.95,13047.0,United Kingdom,2011-12-10 12:50:00
20,536367,48187,DOORMAT NEW ENGLAND,4,2010-12-01 08:34:00,7.95,13047.0,United Kingdom,2011-12-10 12:50:00
21,536368,22960,JAM MAKING SET WITH JARS,6,2010-12-01 08:34:00,4.25,13047.0,United Kingdom,2011-12-10 12:50:00
22,536368,22913,RED COAT RACK PARIS FASHION,3,2010-12-01 08:34:00,4.95,13047.0,United Kingdom,2011-12-10 12:50:00
23,536368,22912,YELLOW COAT RACK PARIS FASHION,3,2010-12-01 08:34:00,4.95,13047.0,United Kingdom,2011-12-10 12:50:00
24,536368,22914,BLUE COAT RACK PARIS FASHION,3,2010-12-01 08:34:00,4.95,13047.0,United Kingdom,2011-12-10 12:50:00
25,536369,21756,BATH BUILDING BLOCK WORD,3,2010-12-01 08:35:00,5.95,13047.0,United Kingdom,2011-12-10 12:50:00
26,536370,22728,ALARM CLOCK BAKELIKE PINK,24,2010-12-01 08:45:00,3.75,12583.0,France,2011-12-10 12:50:00
27,536370,22727,ALARM CLOCK BAKELIKE RED,24,2010-12-01 08:45:00,3.75,12583.0,France,2011-12-10 12:50:00
28,536370,22726,ALARM CLOCK BAKELIKE GREEN,12,2010-12-01 08:45:00,3.75,12583.0,France,2011-12-10 12:50:00
29,536370,21724,PANDA AND BUNNIES STICKER SHEET,12,2010-12-01 08:45:00,0.85,12583.0,France,2011-12-10 12:50:00
...,...,...,...,...,...,...,...,...,...
541879,581585,22726,ALARM CLOCK BAKELIKE GREEN,8,2011-12-09 12:31:00,3.75,15804.0,United Kingdom,2011-12-10 12:50:00
541880,581585,22727,ALARM CLOCK BAKELIKE RED,4,2011-12-09 12:31:00,3.75,15804.0,United Kingdom,2011-12-10 12:50:00
541881,581585,16016,LARGE CHINESE STYLE SCISSOR,10,2011-12-09 12:31:00,0.85,15804.0,United Kingdom,2011-12-10 12:50:00
541882,581585,21916,SET 12 RETRO WHITE CHALK STICKS,24,2011-12-09 12:31:00,0.42,15804.0,United Kingdom,2011-12-10 12:50:00
541883,581585,84692,BOX OF 24 COCKTAIL PARASOLS,25,2011-12-09 12:31:00,0.42,15804.0,United Kingdom,2011-12-10 12:50:00
541884,581585,84946,ANTIQUE SILVER T-LIGHT GLASS,12,2011-12-09 12:31:00,1.25,15804.0,United Kingdom,2011-12-10 12:50:00
541885,581585,21684,SMALL MEDINA STAMPED METAL BOWL,12,2011-12-09 12:31:00,0.85,15804.0,United Kingdom,2011-12-10 12:50:00
541886,581585,22398,MAGNETS PACK OF 4 SWALLOWS,12,2011-12-09 12:31:00,0.39,15804.0,United Kingdom,2011-12-10 12:50:00
541887,581585,23328,SET 6 SCHOOL MILK BOTTLES IN CRATE,4,2011-12-09 12:31:00,3.75,15804.0,United Kingdom,2011-12-10 12:50:00
541888,581585,23145,ZINC T-LIGHT HOLDER STAR LARGE,12,2011-12-09 12:31:00,0.95,15804.0,United Kingdom,2011-12-10 12:50:00
541889,581585,22466,FAIRY TALE COTTAGE NIGHT LIGHT,12,2011-12-09 12:31:00,1.95,15804.0,United Kingdom,2011-12-10 12:50:00
541890,581586,22061,LARGE CAKE STAND HANGING STRAWBERY,8,2011-12-09 12:49:00,2.95,13113.0,United Kingdom,2011-12-10 12:50:00
541891,581586,23275,SET OF 3 HANGING OWLS OLLIE BEAK,24,2011-12-09 12:49:00,1.25,13113.0,United Kingdom,2011-12-10 12:50:00
541892,581586,21217,RED RETROSPOT ROUND CAKE TINS,24,2011-12-09 12:49:00,8.95,13113.0,United Kingdom,2011-12-10 12:50:00
541893,581586,20685,DOORMAT RED RETROSPOT,10,2011-12-09 12:49:00,7.08,13113.0,United Kingdom,2011-12-10 12:50:00
541894,581587,22631,CIRCUS PARADE LUNCH BOX,12,2011-12-09 12:50:00,1.95,12680.0,France,2011-12-10 12:50:00
541895,581587,22556,PLASTERS IN TIN CIRCUS PARADE,12,2011-12-09 12:50:00,1.65,12680.0,France,2011-12-10 12:50:00
541896,581587,22555,PLASTERS IN TIN STRONGMAN,12,2011-12-09 12:50:00,1.65,12680.0,France,2011-12-10 12:50:00
541897,581587,22728,ALARM CLOCK BAKELIKE PINK,4,2011-12-09 12:50:00,3.75,12680.0,France,2011-12-10 12:50:00
541898,581587,22727,ALARM CLOCK BAKELIKE RED,4,2011-12-09 12:50:00,3.75,12680.0,France,2011-12-10 12:50:00
541899,581587,22726,ALARM CLOCK BAKELIKE GREEN,4,2011-12-09 12:50:00,3.75,12680.0,France,2011-12-10 12:50:00
541900,581587,22730,ALARM CLOCK BAKELIKE IVORY,4,2011-12-09 12:50:00,3.75,12680.0,France,2011-12-10 12:50:00
541901,581587,22367,CHILDRENS APRON SPACEBOY DESIGN,8,2011-12-09 12:50:00,1.95,12680.0,France,2011-12-10 12:50:00
541902,581587,22629,SPACEBOY LUNCH BOX,12,2011-12-09 12:50:00,1.95,12680.0,France,2011-12-10 12:50:00
541903,581587,23256,CHILDRENS CUTLERY SPACEBOY,4,2011-12-09 12:50:00,4.15,12680.0,France,2011-12-10 12:50:00
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France,2011-12-10 12:50:00
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France,2011-12-10 12:50:00
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France,2011-12-10 12:50:00
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France,2011-12-10 12:50:00
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France,2011-12-10 12:50:00

In [9]:
rmf['InvoiceDate'].max()

Timestamp('2011-12-09 12:50:00')

In [10]:
rmf['present date'] =  pd.to_datetime(rmf['present date'])

In [11]:
rmf['difference']=rmf['present date']-rmf['InvoiceDate']
rmf

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,present date,difference
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,2011-12-10 12:50:00,374 days 04:24:00
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,2011-12-10 12:50:00,374 days 04:24:00
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,2011-12-10 12:50:00,374 days 04:24:00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,2011-12-10 12:50:00,374 days 04:24:00
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,2011-12-10 12:50:00,374 days 04:24:00
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,2010-12-01 08:26:00,7.65,17850.0,United Kingdom,2011-12-10 12:50:00,374 days 04:24:00
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,2010-12-01 08:26:00,4.25,17850.0,United Kingdom,2011-12-10 12:50:00,374 days 04:24:00
7,536366,22633,HAND WARMER UNION JACK,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom,2011-12-10 12:50:00,374 days 04:22:00
8,536366,22632,HAND WARMER RED POLKA DOT,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom,2011-12-10 12:50:00,374 days 04:22:00
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,2010-12-01 08:34:00,1.69,13047.0,United Kingdom,2011-12-10 12:50:00,374 days 04:16:00
10,536367,22745,POPPY'S PLAYHOUSE BEDROOM,6,2010-12-01 08:34:00,2.10,13047.0,United Kingdom,2011-12-10 12:50:00,374 days 04:16:00
11,536367,22748,POPPY'S PLAYHOUSE KITCHEN,6,2010-12-01 08:34:00,2.10,13047.0,United Kingdom,2011-12-10 12:50:00,374 days 04:16:00
12,536367,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,8,2010-12-01 08:34:00,3.75,13047.0,United Kingdom,2011-12-10 12:50:00,374 days 04:16:00
13,536367,22310,IVORY KNITTED MUG COSY,6,2010-12-01 08:34:00,1.65,13047.0,United Kingdom,2011-12-10 12:50:00,374 days 04:16:00
14,536367,84969,BOX OF 6 ASSORTED COLOUR TEASPOONS,6,2010-12-01 08:34:00,4.25,13047.0,United Kingdom,2011-12-10 12:50:00,374 days 04:16:00
15,536367,22623,BOX OF VINTAGE JIGSAW BLOCKS,3,2010-12-01 08:34:00,4.95,13047.0,United Kingdom,2011-12-10 12:50:00,374 days 04:16:00
16,536367,22622,BOX OF VINTAGE ALPHABET BLOCKS,2,2010-12-01 08:34:00,9.95,13047.0,United Kingdom,2011-12-10 12:50:00,374 days 04:16:00
17,536367,21754,HOME BUILDING BLOCK WORD,3,2010-12-01 08:34:00,5.95,13047.0,United Kingdom,2011-12-10 12:50:00,374 days 04:16:00
18,536367,21755,LOVE BUILDING BLOCK WORD,3,2010-12-01 08:34:00,5.95,13047.0,United Kingdom,2011-12-10 12:50:00,374 days 04:16:00
19,536367,21777,RECIPE BOX WITH METAL HEART,4,2010-12-01 08:34:00,7.95,13047.0,United Kingdom,2011-12-10 12:50:00,374 days 04:16:00
20,536367,48187,DOORMAT NEW ENGLAND,4,2010-12-01 08:34:00,7.95,13047.0,United Kingdom,2011-12-10 12:50:00,374 days 04:16:00
21,536368,22960,JAM MAKING SET WITH JARS,6,2010-12-01 08:34:00,4.25,13047.0,United Kingdom,2011-12-10 12:50:00,374 days 04:16:00
22,536368,22913,RED COAT RACK PARIS FASHION,3,2010-12-01 08:34:00,4.95,13047.0,United Kingdom,2011-12-10 12:50:00,374 days 04:16:00
23,536368,22912,YELLOW COAT RACK PARIS FASHION,3,2010-12-01 08:34:00,4.95,13047.0,United Kingdom,2011-12-10 12:50:00,374 days 04:16:00
24,536368,22914,BLUE COAT RACK PARIS FASHION,3,2010-12-01 08:34:00,4.95,13047.0,United Kingdom,2011-12-10 12:50:00,374 days 04:16:00
25,536369,21756,BATH BUILDING BLOCK WORD,3,2010-12-01 08:35:00,5.95,13047.0,United Kingdom,2011-12-10 12:50:00,374 days 04:15:00
26,536370,22728,ALARM CLOCK BAKELIKE PINK,24,2010-12-01 08:45:00,3.75,12583.0,France,2011-12-10 12:50:00,374 days 04:05:00
27,536370,22727,ALARM CLOCK BAKELIKE RED,24,2010-12-01 08:45:00,3.75,12583.0,France,2011-12-10 12:50:00,374 days 04:05:00
28,536370,22726,ALARM CLOCK BAKELIKE GREEN,12,2010-12-01 08:45:00,3.75,12583.0,France,2011-12-10 12:50:00,374 days 04:05:00
29,536370,21724,PANDA AND BUNNIES STICKER SHEET,12,2010-12-01 08:45:00,0.85,12583.0,France,2011-12-10 12:50:00,374 days 04:05:00
...,...,...,...,...,...,...,...,...,...,...
541879,581585,22726,ALARM CLOCK BAKELIKE GREEN,8,2011-12-09 12:31:00,3.75,15804.0,United Kingdom,2011-12-10 12:50:00,1 days 00:19:00
541880,581585,22727,ALARM CLOCK BAKELIKE RED,4,2011-12-09 12:31:00,3.75,15804.0,United Kingdom,2011-12-10 12:50:00,1 days 00:19:00
541881,581585,16016,LARGE CHINESE STYLE SCISSOR,10,2011-12-09 12:31:00,0.85,15804.0,United Kingdom,2011-12-10 12:50:00,1 days 00:19:00
541882,581585,21916,SET 12 RETRO WHITE CHALK STICKS,24,2011-12-09 12:31:00,0.42,15804.0,United Kingdom,2011-12-10 12:50:00,1 days 00:19:00
541883,581585,84692,BOX OF 24 COCKTAIL PARASOLS,25,2011-12-09 12:31:00,0.42,15804.0,United Kingdom,2011-12-10 12:50:00,1 days 00:19:00
541884,581585,84946,ANTIQUE SILVER T-LIGHT GLASS,12,2011-12-09 12:31:00,1.25,15804.0,United Kingdom,2011-12-10 12:50:00,1 days 00:19:00
541885,581585,21684,SMALL MEDINA STAMPED METAL BOWL,12,2011-12-09 12:31:00,0.85,15804.0,United Kingdom,2011-12-10 12:50:00,1 days 00:19:00
541886,581585,22398,MAGNETS PACK OF 4 SWALLOWS,12,2011-12-09 12:31:00,0.39,15804.0,United Kingdom,2011-12-10 12:50:00,1 days 00:19:00
541887,581585,23328,SET 6 SCHOOL MILK BOTTLES IN CRATE,4,2011-12-09 12:31:00,3.75,15804.0,United Kingdom,2011-12-10 12:50:00,1 days 00:19:00
541888,581585,23145,ZINC T-LIGHT HOLDER STAR LARGE,12,2011-12-09 12:31:00,0.95,15804.0,United Kingdom,2011-12-10 12:50:00,1 days 00:19:00
541889,581585,22466,FAIRY TALE COTTAGE NIGHT LIGHT,12,2011-12-09 12:31:00,1.95,15804.0,United Kingdom,2011-12-10 12:50:00,1 days 00:19:00
541890,581586,22061,LARGE CAKE STAND HANGING STRAWBERY,8,2011-12-09 12:49:00,2.95,13113.0,United Kingdom,2011-12-10 12:50:00,1 days 00:01:00
541891,581586,23275,SET OF 3 HANGING OWLS OLLIE BEAK,24,2011-12-09 12:49:00,1.25,13113.0,United Kingdom,2011-12-10 12:50:00,1 days 00:01:00
541892,581586,21217,RED RETROSPOT ROUND CAKE TINS,24,2011-12-09 12:49:00,8.95,13113.0,United Kingdom,2011-12-10 12:50:00,1 days 00:01:00
541893,581586,20685,DOORMAT RED RETROSPOT,10,2011-12-09 12:49:00,7.08,13113.0,United Kingdom,2011-12-10 12:50:00,1 days 00:01:00
541894,581587,22631,CIRCUS PARADE LUNCH BOX,12,2011-12-09 12:50:00,1.95,12680.0,France,2011-12-10 12:50:00,1 days 00:00:00
541895,581587,22556,PLASTERS IN TIN CIRCUS PARADE,12,2011-12-09 12:50:00,1.65,12680.0,France,2011-12-10 12:50:00,1 days 00:00:00
541896,581587,22555,PLASTERS IN TIN STRONGMAN,12,2011-12-09 12:50:00,1.65,12680.0,France,2011-12-10 12:50:00,1 days 00:00:00
541897,581587,22728,ALARM CLOCK BAKELIKE PINK,4,2011-12-09 12:50:00,3.75,12680.0,France,2011-12-10 12:50:00,1 days 00:00:00
541898,581587,22727,ALARM CLOCK BAKELIKE RED,4,2011-12-09 12:50:00,3.75,12680.0,France,2011-12-10 12:50:00,1 days 00:00:00
541899,581587,22726,ALARM CLOCK BAKELIKE GREEN,4,2011-12-09 12:50:00,3.75,12680.0,France,2011-12-10 12:50:00,1 days 00:00:00
541900,581587,22730,ALARM CLOCK BAKELIKE IVORY,4,2011-12-09 12:50:00,3.75,12680.0,France,2011-12-10 12:50:00,1 days 00:00:00
541901,581587,22367,CHILDRENS APRON SPACEBOY DESIGN,8,2011-12-09 12:50:00,1.95,12680.0,France,2011-12-10 12:50:00,1 days 00:00:00
541902,581587,22629,SPACEBOY LUNCH BOX,12,2011-12-09 12:50:00,1.95,12680.0,France,2011-12-10 12:50:00,1 days 00:00:00
541903,581587,23256,CHILDRENS CUTLERY SPACEBOY,4,2011-12-09 12:50:00,4.15,12680.0,France,2011-12-10 12:50:00,1 days 00:00:00
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France,2011-12-10 12:50:00,1 days 00:00:00
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France,2011-12-10 12:50:00,1 days 00:00:00
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France,2011-12-10 12:50:00,1 days 00:00:00
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France,2011-12-10 12:50:00,1 days 00:00:00
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France,2011-12-10 12:50:00,1 days 00:00:00

In [12]:
rmf['difference']=rmf['difference'].astype('str')

In [13]:
r = rmf['difference'].str.extract('(\d+)', expand=True)
r

          0
0       374
1       374
2       374
3       374
4       374
5       374
6       374
7       374
8       374
9       374
10      374
11      374
12      374
13      374
14      374
15      374
16      374
17      374
18      374
19      374
20      374
21      374
22      374
23      374
24      374
25      374
26      374
27      374
28      374
29      374
...     ...
541879    1
541880    1
541881    1
541882    1
541883    1
541884    1
541885    1
541886    1
541887    1
541888    1
541889    1
541890    1
541891    1
541892    1
541893    1
541894    1
541895    1
541896    1
541897    1
541898    1
541899    1
541900    1
541901    1
541902    1
541903    1
541904    1
541905    1
541906    1
541907    1
541908    1

[541909 rows x 1 columns]

In [14]:
rmf['difference']=r

In [15]:
rmf

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,present date,difference
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,2011-12-10 12:50:00,374
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,2011-12-10 12:50:00,374
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,2011-12-10 12:50:00,374
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,2011-12-10 12:50:00,374
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,2011-12-10 12:50:00,374
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,2010-12-01 08:26:00,7.65,17850.0,United Kingdom,2011-12-10 12:50:00,374
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,2010-12-01 08:26:00,4.25,17850.0,United Kingdom,2011-12-10 12:50:00,374
7,536366,22633,HAND WARMER UNION JACK,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom,2011-12-10 12:50:00,374
8,536366,22632,HAND WARMER RED POLKA DOT,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom,2011-12-10 12:50:00,374
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,2010-12-01 08:34:00,1.69,13047.0,United Kingdom,2011-12-10 12:50:00,374
10,536367,22745,POPPY'S PLAYHOUSE BEDROOM,6,2010-12-01 08:34:00,2.10,13047.0,United Kingdom,2011-12-10 12:50:00,374
11,536367,22748,POPPY'S PLAYHOUSE KITCHEN,6,2010-12-01 08:34:00,2.10,13047.0,United Kingdom,2011-12-10 12:50:00,374
12,536367,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,8,2010-12-01 08:34:00,3.75,13047.0,United Kingdom,2011-12-10 12:50:00,374
13,536367,22310,IVORY KNITTED MUG COSY,6,2010-12-01 08:34:00,1.65,13047.0,United Kingdom,2011-12-10 12:50:00,374
14,536367,84969,BOX OF 6 ASSORTED COLOUR TEASPOONS,6,2010-12-01 08:34:00,4.25,13047.0,United Kingdom,2011-12-10 12:50:00,374
15,536367,22623,BOX OF VINTAGE JIGSAW BLOCKS,3,2010-12-01 08:34:00,4.95,13047.0,United Kingdom,2011-12-10 12:50:00,374
16,536367,22622,BOX OF VINTAGE ALPHABET BLOCKS,2,2010-12-01 08:34:00,9.95,13047.0,United Kingdom,2011-12-10 12:50:00,374
17,536367,21754,HOME BUILDING BLOCK WORD,3,2010-12-01 08:34:00,5.95,13047.0,United Kingdom,2011-12-10 12:50:00,374
18,536367,21755,LOVE BUILDING BLOCK WORD,3,2010-12-01 08:34:00,5.95,13047.0,United Kingdom,2011-12-10 12:50:00,374
19,536367,21777,RECIPE BOX WITH METAL HEART,4,2010-12-01 08:34:00,7.95,13047.0,United Kingdom,2011-12-10 12:50:00,374
20,536367,48187,DOORMAT NEW ENGLAND,4,2010-12-01 08:34:00,7.95,13047.0,United Kingdom,2011-12-10 12:50:00,374
21,536368,22960,JAM MAKING SET WITH JARS,6,2010-12-01 08:34:00,4.25,13047.0,United Kingdom,2011-12-10 12:50:00,374
22,536368,22913,RED COAT RACK PARIS FASHION,3,2010-12-01 08:34:00,4.95,13047.0,United Kingdom,2011-12-10 12:50:00,374
23,536368,22912,YELLOW COAT RACK PARIS FASHION,3,2010-12-01 08:34:00,4.95,13047.0,United Kingdom,2011-12-10 12:50:00,374
24,536368,22914,BLUE COAT RACK PARIS FASHION,3,2010-12-01 08:34:00,4.95,13047.0,United Kingdom,2011-12-10 12:50:00,374
25,536369,21756,BATH BUILDING BLOCK WORD,3,2010-12-01 08:35:00,5.95,13047.0,United Kingdom,2011-12-10 12:50:00,374
26,536370,22728,ALARM CLOCK BAKELIKE PINK,24,2010-12-01 08:45:00,3.75,12583.0,France,2011-12-10 12:50:00,374
27,536370,22727,ALARM CLOCK BAKELIKE RED,24,2010-12-01 08:45:00,3.75,12583.0,France,2011-12-10 12:50:00,374
28,536370,22726,ALARM CLOCK BAKELIKE GREEN,12,2010-12-01 08:45:00,3.75,12583.0,France,2011-12-10 12:50:00,374
29,536370,21724,PANDA AND BUNNIES STICKER SHEET,12,2010-12-01 08:45:00,0.85,12583.0,France,2011-12-10 12:50:00,374
...,...,...,...,...,...,...,...,...,...,...
541879,581585,22726,ALARM CLOCK BAKELIKE GREEN,8,2011-12-09 12:31:00,3.75,15804.0,United Kingdom,2011-12-10 12:50:00,1
541880,581585,22727,ALARM CLOCK BAKELIKE RED,4,2011-12-09 12:31:00,3.75,15804.0,United Kingdom,2011-12-10 12:50:00,1
541881,581585,16016,LARGE CHINESE STYLE SCISSOR,10,2011-12-09 12:31:00,0.85,15804.0,United Kingdom,2011-12-10 12:50:00,1
541882,581585,21916,SET 12 RETRO WHITE CHALK STICKS,24,2011-12-09 12:31:00,0.42,15804.0,United Kingdom,2011-12-10 12:50:00,1
541883,581585,84692,BOX OF 24 COCKTAIL PARASOLS,25,2011-12-09 12:31:00,0.42,15804.0,United Kingdom,2011-12-10 12:50:00,1
541884,581585,84946,ANTIQUE SILVER T-LIGHT GLASS,12,2011-12-09 12:31:00,1.25,15804.0,United Kingdom,2011-12-10 12:50:00,1
541885,581585,21684,SMALL MEDINA STAMPED METAL BOWL,12,2011-12-09 12:31:00,0.85,15804.0,United Kingdom,2011-12-10 12:50:00,1
541886,581585,22398,MAGNETS PACK OF 4 SWALLOWS,12,2011-12-09 12:31:00,0.39,15804.0,United Kingdom,2011-12-10 12:50:00,1
541887,581585,23328,SET 6 SCHOOL MILK BOTTLES IN CRATE,4,2011-12-09 12:31:00,3.75,15804.0,United Kingdom,2011-12-10 12:50:00,1
541888,581585,23145,ZINC T-LIGHT HOLDER STAR LARGE,12,2011-12-09 12:31:00,0.95,15804.0,United Kingdom,2011-12-10 12:50:00,1
541889,581585,22466,FAIRY TALE COTTAGE NIGHT LIGHT,12,2011-12-09 12:31:00,1.95,15804.0,United Kingdom,2011-12-10 12:50:00,1
541890,581586,22061,LARGE CAKE STAND HANGING STRAWBERY,8,2011-12-09 12:49:00,2.95,13113.0,United Kingdom,2011-12-10 12:50:00,1
541891,581586,23275,SET OF 3 HANGING OWLS OLLIE BEAK,24,2011-12-09 12:49:00,1.25,13113.0,United Kingdom,2011-12-10 12:50:00,1
541892,581586,21217,RED RETROSPOT ROUND CAKE TINS,24,2011-12-09 12:49:00,8.95,13113.0,United Kingdom,2011-12-10 12:50:00,1
541893,581586,20685,DOORMAT RED RETROSPOT,10,2011-12-09 12:49:00,7.08,13113.0,United Kingdom,2011-12-10 12:50:00,1
541894,581587,22631,CIRCUS PARADE LUNCH BOX,12,2011-12-09 12:50:00,1.95,12680.0,France,2011-12-10 12:50:00,1
541895,581587,22556,PLASTERS IN TIN CIRCUS PARADE,12,2011-12-09 12:50:00,1.65,12680.0,France,2011-12-10 12:50:00,1
541896,581587,22555,PLASTERS IN TIN STRONGMAN,12,2011-12-09 12:50:00,1.65,12680.0,France,2011-12-10 12:50:00,1
541897,581587,22728,ALARM CLOCK BAKELIKE PINK,4,2011-12-09 12:50:00,3.75,12680.0,France,2011-12-10 12:50:00,1
541898,581587,22727,ALARM CLOCK BAKELIKE RED,4,2011-12-09 12:50:00,3.75,12680.0,France,2011-12-10 12:50:00,1
541899,581587,22726,ALARM CLOCK BAKELIKE GREEN,4,2011-12-09 12:50:00,3.75,12680.0,France,2011-12-10 12:50:00,1
541900,581587,22730,ALARM CLOCK BAKELIKE IVORY,4,2011-12-09 12:50:00,3.75,12680.0,France,2011-12-10 12:50:00,1
541901,581587,22367,CHILDRENS APRON SPACEBOY DESIGN,8,2011-12-09 12:50:00,1.95,12680.0,France,2011-12-10 12:50:00,1
541902,581587,22629,SPACEBOY LUNCH BOX,12,2011-12-09 12:50:00,1.95,12680.0,France,2011-12-10 12:50:00,1
541903,581587,23256,CHILDRENS CUTLERY SPACEBOY,4,2011-12-09 12:50:00,4.15,12680.0,France,2011-12-10 12:50:00,1
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France,2011-12-10 12:50:00,1
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France,2011-12-10 12:50:00,1
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France,2011-12-10 12:50:00,1
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France,2011-12-10 12:50:00,1
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France,2011-12-10 12:50:00,1

In [16]:
rmf['difference']=rmf['difference'].astype('int')

In [17]:
r=rmf.groupby(['CustomerID'])['difference'].min()
r

CustomerID
12346.0    326
12347.0      2
12348.0     75
12349.0     19
12350.0    310
12352.0     36
12353.0    204
12354.0    232
12355.0    214
12356.0     23
12357.0     33
12358.0      2
12359.0      8
12360.0     52
12361.0    287
12362.0      3
12363.0    110
12364.0      8
12365.0    291
12367.0      4
12370.0     51
12371.0     45
12372.0     72
12373.0    311
12374.0     25
12375.0      3
12377.0    315
12378.0    130
12379.0     82
12380.0     22
          ...
18245.0      7
18246.0     24
18248.0    114
18249.0     17
18250.0    301
18251.0     87
18252.0     51
18255.0     89
18256.0    355
18257.0     39
18259.0     25
18260.0    173
18261.0     43
18262.0    140
18263.0     23
18265.0     72
18268.0    134
18269.0    358
18270.0     38
18272.0      3
18273.0      2
18274.0     18
18276.0     21
18277.0     58
18278.0     74
18280.0    278
18281.0    181
18282.0      8
18283.0      4
18287.0     43
Name: difference, Length: 4372, dtype: int32

In [18]:
r=pd.DataFrame(r)
r

            difference
CustomerID
12346.0            326
12347.0              2
12348.0             75
12349.0             19
12350.0            310
12352.0             36
12353.0            204
12354.0            232
12355.0            214
12356.0             23
12357.0             33
12358.0              2
12359.0              8
12360.0             52
12361.0            287
12362.0              3
12363.0            110
12364.0              8
12365.0            291
12367.0              4
12370.0             51
12371.0             45
12372.0             72
12373.0            311
12374.0             25
12375.0              3
12377.0            315
12378.0            130
12379.0             82
12380.0             22
...                ...
18245.0              7
18246.0             24
18248.0            114
18249.0             17
18250.0            301
18251.0             87
18252.0             51
18255.0             89
18256.0            355
18257.0             39
18259.0             25
18260.0            173
18261.0             43
18262.0            140
18263.0             23
18265.0             72
18268.0            134
18269.0            358
18270.0             38
18272.0              3
18273.0              2
18274.0             18
18276.0             21
18277.0             58
18278.0             74
18280.0            278
18281.0            181
18282.0              8
18283.0              4
18287.0             43

[4372 rows x 1 columns]

In [19]:
r.rename(columns={'difference':'recency'},inplace=True)
r

            recency
CustomerID
12346.0         326
12347.0           2
12348.0          75
12349.0          19
12350.0         310
12352.0          36
12353.0         204
12354.0         232
12355.0         214
12356.0          23
12357.0          33
12358.0           2
12359.0           8
12360.0          52
12361.0         287
12362.0           3
12363.0         110
12364.0           8
12365.0         291
12367.0           4
12370.0          51
12371.0          45
12372.0          72
12373.0         311
12374.0          25
12375.0           3
12377.0         315
12378.0         130
12379.0          82
12380.0          22
...             ...
18245.0           7
18246.0          24
18248.0         114
18249.0          17
18250.0         301
18251.0          87
18252.0          51
18255.0          89
18256.0         355
18257.0          39
18259.0          25
18260.0         173
18261.0          43
18262.0         140
18263.0          23
18265.0          72
18268.0         134
18269.0         358
18270.0          38
18272.0           3
18273.0           2
18274.0          18
18276.0          21
18277.0          58
18278.0          74
18280.0         278
18281.0         181
18282.0           8
18283.0           4
18287.0          43

[4372 rows x 1 columns]

In [20]:
rmf.dtypes

InvoiceNo               object
StockCode               object
Description             object
Quantity                 int64
InvoiceDate     datetime64[ns]
UnitPrice              float64
CustomerID             float64
Country                 object
present date    datetime64[ns]
difference               int32
dtype: object

In [21]:
f=rmf.drop_duplicates(subset=['InvoiceNo','CustomerID'],keep='first').groupby(['CustomerID'])[['InvoiceNo']].count().sort_values('InvoiceNo',ascending=False)
f

            InvoiceNo
CustomerID
14911.0           248
12748.0           224
17841.0           169
14606.0           128
13089.0           118
15311.0           118
12971.0            89
14527.0            86
13408.0            81
14646.0            77
16029.0            76
16422.0            75
14156.0            66
13798.0            63
18102.0            62
13694.0            60
17450.0            55
15061.0            55
16013.0            54
15189.0            53
15039.0            52
13767.0            52
17949.0            52
17811.0            51
12921.0            50
12471.0            49
16133.0            46
17511.0            46
14298.0            45
17315.0            43
...               ...
16337.0             1
13934.0             1
13937.0             1
13889.0             1
16392.0             1
13845.0             1
13866.0             1
16445.0             1
16433.0             1
16432.0             1
13858.0             1
16430.0             1
16429.0             1
16428.0             1
13859.0             1
16425.0             1
16423.0             1
16415.0             1
13887.0             1
16413.0             1
16412.0             1
13874.0             1
13876.0             1
16406.0             1
16404.0             1
13877.0             1
16400.0             1
13878.0             1
13886.0             1
13670.0             1

[4372 rows x 1 columns]

In [22]:
rmf['price']=rmf['Quantity']*rmf['UnitPrice']

In [23]:
m=rmf.groupby(['CustomerID'])[['price']].sum().sort_values('price',ascending=False)
m

                price
CustomerID
14646.0     279489.02
18102.0     256438.49
17450.0     187482.17
14911.0     132572.62
12415.0     123725.45
14156.0     113384.14
17511.0      88125.38
16684.0      65892.08
13694.0      62653.10
15311.0      59419.34
13089.0      57385.88
14096.0      57120.91
15061.0      54228.74
17949.0      52750.84
15769.0      51823.72
16029.0      50992.61
14298.0      50862.44
14088.0      50415.49
17841.0      40340.78
13798.0      36351.42
16422.0      33805.69
12931.0      33462.81
16013.0      33366.25
15838.0      33350.76
17389.0      31300.08
17404.0      30300.82
12748.0      29072.10
13098.0      28658.88
13081.0      27964.48
13408.0      27487.41
...               ...
14119.0        -19.90
14627.0        -21.85
17820.0        -24.05
16061.0        -29.95
15590.0        -30.19
16579.0        -30.60
16262.0        -31.65
13693.0        -32.00
18141.0        -35.40
14437.0        -43.40
18256.0        -50.10
13672.0        -71.46
15638.0        -94.00
16546.0        -95.93
13829.0       -102.00
13958.0       -102.45
17065.0       -112.35
15728.0       -134.80
17548.0       -141.48
17307.0       -152.64
12666.0       -227.44
16252.0       -295.09
15802.0       -451.42
13154.0       -611.86
15823.0       -840.76
12503.0      -1126.00
17603.0      -1165.30
14213.0      -1192.20
15369.0      -1592.49
17448.0      -4287.63

[4372 rows x 1 columns]

In [24]:
m['price'].min()

-4287.63

In [25]:
m['price'].quantile(0.8)

2002.092

In [26]:
m['price'].quantile([0.0,0.2,0.4,0.6,0.8,1.0])

0.0     -4287.630
0.2       234.392
0.4       465.412
0.6       909.134
0.8      2002.092
1.0    279489.020
Name: price, dtype: float64

In [27]:
m1=m.loc[m['price']>0]
m1

                   price
CustomerID
14646.0     2.794890e+05
18102.0     2.564385e+05
17450.0     1.874822e+05
14911.0     1.325726e+05
12415.0     1.237254e+05
14156.0     1.133841e+05
17511.0     8.812538e+04
16684.0     6.589208e+04
13694.0     6.265310e+04
15311.0     5.941934e+04
13089.0     5.738588e+04
14096.0     5.712091e+04
15061.0     5.422874e+04
17949.0     5.275084e+04
15769.0     5.182372e+04
16029.0     5.099261e+04
14298.0     5.086244e+04
14088.0     5.041549e+04
17841.0     4.034078e+04
13798.0     3.635142e+04
16422.0     3.380569e+04
12931.0     3.346281e+04
16013.0     3.336625e+04
15838.0     3.335076e+04
17389.0     3.130008e+04
17404.0     3.030082e+04
12748.0     2.907210e+04
13098.0     2.865888e+04
13081.0     2.796448e+04
13408.0     2.748741e+04
...                  ...
12977.0     3.924000e+01
16659.0     3.912000e+01
18019.0     3.845000e+01
12855.0     3.810000e+01
16162.0     3.740000e+01
17816.0     3.656000e+01
16856.0     3.540000e+01
14576.0     3.540000e+01
17831.0     3.540000e+01
15744.0     3.480000e+01
16765.0     3.400000e+01
17408.0     3.265000e+01
15940.0     3.180000e+01
13120.0     3.060000e+01
15657.0     3.000000e+01
17102.0     2.550000e+01
16953.0     2.080000e+01
17986.0     2.080000e+01
16093.0     1.700000e+01
13307.0     1.500000e+01
17763.0     1.500000e+01
17900.0     1.500000e+01
17956.0     1.275000e+01
16738.0     3.750000e+00
16446.0     2.900000e+00
12607.0     3.339551e-13
13762.0     4.263256e-14
12558.0     2.664535e-14
13364.0     2.131628e-14
18274.0     1.243450e-14

[4322 rows x 1 columns]

In [28]:
m.dtypes

price    float64
dtype: object

In [29]:
m1['price'].min()

1.2434497875801753e-14

In [30]:
rating1=m1[['price']].drop_duplicates()
rating1=rating1[rating1['price'] > 0]
rating1['monetary_Band'] = pd.qcut(rating1['price'], 5)
rating1=rating1[['monetary_Band']].drop_duplicates()
rating1

                           monetary_Band
CustomerID
14646.0             (2043.72, 279489.02]
13450.0                (937.92, 2043.72]
17097.0                 (488.03, 937.92]
13984.0                  (250.0, 488.03]
15510.0     (-0.0009999999999876, 250.0]

In [31]:
m1['price'].quantile([0.2,0.4,0.6,0.8,1.0])

0.2       245.242
0.4       481.510
0.6       919.358
0.8      2021.560
1.0    279489.020
Name: price, dtype: float64

In [32]:
def func(x):
    if 0<= x <=245.242:
        return 1
    if 245.242< x <=481.510:
        return 2
    if 481.510 < x <=919.358:
        return 3
    if 919.358 < x <=2021.560:
        return 4
    if 2021.560 < x <=279489.020:
        return 5

In [33]:
m1['mscore']=m1.applymap(func)

C:\Users\DELL3521\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [34]:
m1.rename(columns={'price':'monetory'},inplace=True)
m1

C:\Users\DELL3521\Anaconda3\lib\site-packages\pandas\core\frame.py:3778: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)

                monetory  mscore
CustomerID
14646.0     2.794890e+05       5
18102.0     2.564385e+05       5
17450.0     1.874822e+05       5
14911.0     1.325726e+05       5
12415.0     1.237254e+05       5
14156.0     1.133841e+05       5
17511.0     8.812538e+04       5
16684.0     6.589208e+04       5
13694.0     6.265310e+04       5
15311.0     5.941934e+04       5
13089.0     5.738588e+04       5
14096.0     5.712091e+04       5
15061.0     5.422874e+04       5
17949.0     5.275084e+04       5
15769.0     5.182372e+04       5
16029.0     5.099261e+04       5
14298.0     5.086244e+04       5
14088.0     5.041549e+04       5
17841.0     4.034078e+04       5
13798.0     3.635142e+04       5
16422.0     3.380569e+04       5
12931.0     3.346281e+04       5
16013.0     3.336625e+04       5
15838.0     3.335076e+04       5
17389.0     3.130008e+04       5
17404.0     3.030082e+04       5
12748.0     2.907210e+04       5
13098.0     2.865888e+04       5
13081.0     2.796448e+04       5
13408.0     2.748741e+04       5
...                  ...     ...
12977.0     3.924000e+01       1
16659.0     3.912000e+01       1
18019.0     3.845000e+01       1
12855.0     3.810000e+01       1
16162.0     3.740000e+01       1
17816.0     3.656000e+01       1
16856.0     3.540000e+01       1
14576.0     3.540000e+01       1
17831.0     3.540000e+01       1
15744.0     3.480000e+01       1
16765.0     3.400000e+01       1
17408.0     3.265000e+01       1
15940.0     3.180000e+01       1
13120.0     3.060000e+01       1
15657.0     3.000000e+01       1
17102.0     2.550000e+01       1
16953.0     2.080000e+01       1
17986.0     2.080000e+01       1
16093.0     1.700000e+01       1
13307.0     1.500000e+01       1
17763.0     1.500000e+01       1
17900.0     1.500000e+01       1
17956.0     1.275000e+01       1
16738.0     3.750000e+00       1
16446.0     2.900000e+00       1
12607.0     3.339551e-13       1
13762.0     4.263256e-14       1
12558.0     2.664535e-14       1
13364.0     2.131628e-14       1
18274.0     1.243450e-14       1

[4322 rows x 2 columns]

In [35]:
f.rename(columns={'InvoiceNo':'frequency'},inplace=True)
f

            frequency
CustomerID
14911.0           248
12748.0           224
17841.0           169
14606.0           128
13089.0           118
15311.0           118
12971.0            89
14527.0            86
13408.0            81
14646.0            77
16029.0            76
16422.0            75
14156.0            66
13798.0            63
18102.0            62
13694.0            60
17450.0            55
15061.0            55
16013.0            54
15189.0            53
15039.0            52
13767.0            52
17949.0            52
17811.0            51
12921.0            50
12471.0            49
16133.0            46
17511.0            46
14298.0            45
17315.0            43
...               ...
16337.0             1
13934.0             1
13937.0             1
13889.0             1
16392.0             1
13845.0             1
13866.0             1
16445.0             1
16433.0             1
16432.0             1
13858.0             1
16430.0             1
16429.0             1
16428.0             1
13859.0             1
16425.0             1
16423.0             1
16415.0             1
13887.0             1
16413.0             1
16412.0             1
13874.0             1
13876.0             1
16406.0             1
16404.0             1
13877.0             1
16400.0             1
13878.0             1
13886.0             1
13670.0             1

[4372 rows x 1 columns]

In [36]:
f['frequency'].quantile([0.2,0.4,0.6,0.8,1.0])

0.2      1.0
0.4      2.0
0.6      4.0
0.8      7.0
1.0    248.0
Name: frequency, dtype: float64

In [37]:
def func(x):
    if 0<= x <=1.0:
        return 1
    if 1.0< x <=2.0:
        return 2
    if 2.0 < x <=4.0:
        return 3
    if 4.0 < x <=7.0:
        return 4
    if 7.0 < x <=248.0:
        return 5

In [38]:
f['fscore']=f.applymap(func)

In [39]:
f

            frequency  fscore
CustomerID
14911.0           248       5
12748.0           224       5
17841.0           169       5
14606.0           128       5
13089.0           118       5
15311.0           118       5
12971.0            89       5
14527.0            86       5
13408.0            81       5
14646.0            77       5
16029.0            76       5
16422.0            75       5
14156.0            66       5
13798.0            63       5
18102.0            62       5
13694.0            60       5
17450.0            55       5
15061.0            55       5
16013.0            54       5
15189.0            53       5
15039.0            52       5
13767.0            52       5
17949.0            52       5
17811.0            51       5
12921.0            50       5
12471.0            49       5
16133.0            46       5
17511.0            46       5
14298.0            45       5
17315.0            43       5
...               ...     ...
16337.0             1       1
13934.0             1       1
13937.0             1       1
13889.0             1       1
16392.0             1       1
13845.0             1       1
13866.0             1       1
16445.0             1       1
16433.0             1       1
16432.0             1       1
13858.0             1       1
16430.0             1       1
16429.0             1       1
16428.0             1       1
13859.0             1       1
16425.0             1       1
16423.0             1       1
16415.0             1       1
13887.0             1       1
16413.0             1       1
16412.0             1       1
13874.0             1       1
13876.0             1       1
16406.0             1       1
16404.0             1       1
13877.0             1       1
16400.0             1       1
13878.0             1       1
13886.0             1       1
13670.0             1       1

[4372 rows x 2 columns]

In [40]:
r

            recency
CustomerID
12346.0         326
12347.0           2
12348.0          75
12349.0          19
12350.0         310
12352.0          36
12353.0         204
12354.0         232
12355.0         214
12356.0          23
12357.0          33
12358.0           2
12359.0           8
12360.0          52
12361.0         287
12362.0           3
12363.0         110
12364.0           8
12365.0         291
12367.0           4
12370.0          51
12371.0          45
12372.0          72
12373.0         311
12374.0          25
12375.0           3
12377.0         315
12378.0         130
12379.0          82
12380.0          22
...             ...
18245.0           7
18246.0          24
18248.0         114
18249.0          17
18250.0         301
18251.0          87
18252.0          51
18255.0          89
18256.0         355
18257.0          39
18259.0          25
18260.0         173
18261.0          43
18262.0         140
18263.0          23
18265.0          72
18268.0         134
18269.0         358
18270.0          38
18272.0           3
18273.0           2
18274.0          18
18276.0          21
18277.0          58
18278.0          74
18280.0         278
18281.0         181
18282.0           8
18283.0           4
18287.0          43

[4372 rows x 1 columns]

In [41]:
r['recency'].quantile([0.2,0.4,0.6,0.8,1.0])

0.2     11.0
0.4     32.0
0.6     71.0
0.8    178.8
1.0    374.0
Name: recency, dtype: float64

In [42]:
def func(x):
    if 0<= x <=30.0:
        return 5
    if 30.0< x <=109.0:
        return 4
    if 109.0 < x <=148.0:
        return 3
    if 148.0 < x <=218.0:
        return 2
    if 218.0 < x <=374.0:
        return 1

In [43]:
r['rscore']=r.applymap(func)

In [44]:
r

            recency  rscore
CustomerID
12346.0         326       1
12347.0           2       5
12348.0          75       4
12349.0          19       5
12350.0         310       1
12352.0          36       4
12353.0         204       2
12354.0         232       1
12355.0         214       2
12356.0          23       5
12357.0          33       4
12358.0           2       5
12359.0           8       5
12360.0          52       4
12361.0         287       1
12362.0           3       5
12363.0         110       3
12364.0           8       5
12365.0         291       1
12367.0           4       5
12370.0          51       4
12371.0          45       4
12372.0          72       4
12373.0         311       1
12374.0          25       5
12375.0           3       5
12377.0         315       1
12378.0         130       3
12379.0          82       4
12380.0          22       5
...             ...     ...
18245.0           7       5
18246.0          24       5
18248.0         114       3
18249.0          17       5
18250.0         301       1
18251.0          87       4
18252.0          51       4
18255.0          89       4
18256.0         355       1
18257.0          39       4
18259.0          25       5
18260.0         173       2
18261.0          43       4
18262.0         140       3
18263.0          23       5
18265.0          72       4
18268.0         134       3
18269.0         358       1
18270.0          38       4
18272.0           3       5
18273.0           2       5
18274.0          18       5
18276.0          21       5
18277.0          58       4
18278.0          74       4
18280.0         278       1
18281.0         181       2
18282.0           8       5
18283.0           4       5
18287.0          43       4

[4372 rows x 2 columns]

In [45]:
rfm1=r.merge(f,on='CustomerID').merge(m1,on='CustomerID')
rfm1

            recency  rscore  frequency  fscore      monetory  mscore
CustomerID
12347.0           2       5          7       4  4.310000e+03       5
12348.0          75       4          4       3  1.797240e+03       4
12349.0          19       5          1       1  1.757550e+03       4
12350.0         310       1          1       1  3.344000e+02       2
12352.0          36       4         11       5  1.545410e+03       4
12353.0         204       2          1       1  8.900000e+01       1
12354.0         232       1          1       1  1.079400e+03       4
12355.0         214       2          1       1  4.594000e+02       2
12356.0          23       5          3       3  2.811430e+03       5
12357.0          33       4          1       1  6.207670e+03       5
12358.0           2       5          2       2  1.168060e+03       4
12359.0           8       5          6       4  6.245530e+03       5
12360.0          52       4          3       3  2.662060e+03       5
12361.0         287       1          1       1  1.899000e+02       1
12362.0           3       5         13       5  5.154580e+03       5
12363.0         110       3          2       2  5.520000e+02       3
12364.0           8       5          4       3  1.313100e+03       4
12365.0         291       1          3       3  3.206900e+02       2
12367.0           4       5          1       1  1.689000e+02       1
12370.0          51       4          4       3  3.545690e+03       5
12371.0          45       4          2       2  1.887960e+03       4
12372.0          72       4          3       3  1.298040e+03       4
12373.0         311       1          1       1  3.646000e+02       2
12374.0          25       5          1       1  7.429300e+02       3
12375.0           3       5          3       3  4.554200e+02       2
12377.0         315       1          2       2  1.628120e+03       4
12378.0         130       3          1       1  4.008620e+03       5
12379.0          82       4          3       3  8.502900e+02       3
12380.0          22       5          5       4  2.720560e+03       5
12381.0           5       5          6       4  1.803960e+03       4
...             ...     ...        ...     ...           ...     ...
18241.0          10       5         18       5  2.058090e+03       5
18242.0          72       4          4       3  2.232490e+03       5
18245.0           7       5          8       5  2.507560e+03       5
18246.0          24       5          2       2  5.961000e+02       3
18248.0         114       3          4       3  7.830200e+02       3
18249.0          17       5          1       1  9.534000e+01       1
18250.0         301       1          2       2  3.429200e+02       2
18251.0          87       4          1       1  4.314720e+03       5
18252.0          51       4          2       2  5.266700e+02       3
18255.0          89       4          1       1  1.033000e+02       1
18257.0          39       4         12       5  2.265380e+03       5
18259.0          25       5          3       3  2.338600e+03       5
18260.0         173       2          8       5  2.595000e+03       5
18261.0          43       4          2       2  3.242400e+02       2
18262.0         140       3          1       1  1.494800e+02       1
18263.0          23       5          4       3  1.211080e+03       4
18265.0          72       4          2       2  8.015100e+02       3
18269.0         358       1          2       2  1.389000e+02       1
18270.0          38       4          3       3  2.389500e+02       1
18272.0           3       5          7       4  3.064780e+03       5
18273.0           2       5          3       3  2.040000e+02       1
18274.0          18       5          2       2  1.243450e-14       1
18276.0          21       5          3       3  3.233600e+02       2
18277.0          58       4          2       2  9.763000e+01       1
18278.0          74       4          1       1  1.739000e+02       1
18280.0         278       1          1       1  1.806000e+02       1
18281.0         181       2          1       1  8.082000e+01       1
18282.0           8       5          3       3  1.766000e+02       1
18283.0           4       5         16       5  2.094880e+03       5
18287.0          43       4          3       3  1.837280e+03       4

[4322 rows x 6 columns]

In [46]:
rfm1['rscore']=rfm1['rscore'].astype('str')
rfm1['fscore']=rfm1['fscore'].astype('str')
rfm1['mscore']=rfm1['mscore'].astype('str')

In [47]:
rfm1['rfmscore']=rfm1['rscore']+rfm1['fscore']+rfm1['mscore']
rfm1

            recency rscore  frequency fscore      monetory mscore rfmscore
CustomerID
12347.0           2      5          7      4  4.310000e+03      5      545
12348.0          75      4          4      3  1.797240e+03      4      434
12349.0          19      5          1      1  1.757550e+03      4      514
12350.0         310      1          1      1  3.344000e+02      2      112
12352.0          36      4         11      5  1.545410e+03      4      454
12353.0         204      2          1      1  8.900000e+01      1      211
12354.0         232      1          1      1  1.079400e+03      4      114
12355.0         214      2          1      1  4.594000e+02      2      212
12356.0          23      5          3      3  2.811430e+03      5      535
12357.0          33      4          1      1  6.207670e+03      5      415
12358.0           2      5          2      2  1.168060e+03      4      524
12359.0           8      5          6      4  6.245530e+03      5      545
12360.0          52      4          3      3  2.662060e+03      5      435
12361.0         287      1          1      1  1.899000e+02      1      111
12362.0           3      5         13      5  5.154580e+03      5      555
12363.0         110      3          2      2  5.520000e+02      3      323
12364.0           8      5          4      3  1.313100e+03      4      534
12365.0         291      1          3      3  3.206900e+02      2      132
12367.0           4      5          1      1  1.689000e+02      1      511
12370.0          51      4          4      3  3.545690e+03      5      435
12371.0          45      4          2      2  1.887960e+03      4      424
12372.0          72      4          3      3  1.298040e+03      4      434
12373.0         311      1          1      1  3.646000e+02      2      112
12374.0          25      5          1      1  7.429300e+02      3      513
12375.0           3      5          3      3  4.554200e+02      2      532
12377.0         315      1          2      2  1.628120e+03      4      124
12378.0         130      3          1      1  4.008620e+03      5      315
12379.0          82      4          3      3  8.502900e+02      3      433
12380.0          22      5          5      4  2.720560e+03      5      545
12381.0           5      5          6      4  1.803960e+03      4      544
...             ...    ...        ...    ...           ...    ...      ...
18241.0          10      5         18      5  2.058090e+03      5      555
18242.0          72      4          4      3  2.232490e+03      5      435
18245.0           7      5          8      5  2.507560e+03      5      555
18246.0          24      5          2      2  5.961000e+02      3      523
18248.0         114      3          4      3  7.830200e+02      3      333
18249.0          17      5          1      1  9.534000e+01      1      511
18250.0         301      1          2      2  3.429200e+02      2      122
18251.0          87      4          1      1  4.314720e+03      5      415
18252.0          51      4          2      2  5.266700e+02      3      423
18255.0          89      4          1      1  1.033000e+02      1      411
18257.0          39      4         12      5  2.265380e+03      5      455
18259.0          25      5          3      3  2.338600e+03      5      535
18260.0         173      2          8      5  2.595000e+03      5      255
18261.0          43      4          2      2  3.242400e+02      2      422
18262.0         140      3          1      1  1.494800e+02      1      311
18263.0          23      5          4      3  1.211080e+03      4      534
18265.0          72      4          2      2  8.015100e+02      3      423
18269.0         358      1          2      2  1.389000e+02      1      121
18270.0          38      4          3      3  2.389500e+02      1      431
18272.0           3      5          7      4  3.064780e+03      5      545
18273.0           2      5          3      3  2.040000e+02      1      531
18274.0          18      5          2      2  1.243450e-14      1      521
18276.0          21      5          3      3  3.233600e+02      2      532
18277.0          58      4          2      2  9.763000e+01      1      421
18278.0          74      4          1      1  1.739000e+02      1      411
18280.0         278      1          1      1  1.806000e+02      1      111
18281.0         181      2          1      1  8.082000e+01      1      211
18282.0           8      5          3      3  1.766000e+02      1      531
18283.0           4      5         16      5  2.094880e+03      5      555
18287.0          43      4          3      3  1.837280e+03      4      434

[4322 rows x 7 columns]

In [48]:
rfm1['fscore']=rfm1['fscore'].astype('int')
rfm1['mscore']=rfm1['mscore'].astype('int')

In [49]:
rfm1['fmscore']=(rfm1['fscore']+rfm1['mscore'])/2
rfm1

,recency,rscore,frequency,fscore,monetory,mscore,rfmscore,fmscore
CustomerID,,,,,,,,
12347.0,2,5,7,4,4.310000e+03,5,545,4.5
12348.0,75,4,4,3,1.797240e+03,4,434,3.5
12349.0,19,5,1,1,1.757550e+03,4,514,2.5
12350.0,310,1,1,1,3.344000e+02,2,112,1.5
12352.0,36,4,11,5,1.545410e+03,4,454,4.5
12353.0,204,2,1,1,8.900000e+01,1,211,1.0
12354.0,232,1,1,1,1.079400e+03,4,114,2.5
12355.0,214,2,1,1,4.594000e+02,2,212,1.5
12356.0,23,5,3,3,2.811430e+03,5,535,4.0
12357.0,33,4,1,1,6.207670e+03,5,415,3.0
12358.0,2,5,2,2,1.168060e+03,4,524,3.0
12359.0,8,5,6,4,6.245530e+03,5,545,4.5
12360.0,52,4,3,3,2.662060e+03,5,435,4.0
12361.0,287,1,1,1,1.899000e+02,1,111,1.0
12362.0,3,5,13,5,5.154580e+03,5,555,5.0
12363.0,110,3,2,2,5.520000e+02,3,323,2.5
12364.0,8,5,4,3,1.313100e+03,4,534,3.5
12365.0,291,1,3,3,3.206900e+02,2,132,2.5
12367.0,4,5,1,1,1.689000e+02,1,511,1.0
12370.0,51,4,4,3,3.545690e+03,5,435,4.0
12371.0,45,4,2,2,1.887960e+03,4,424,3.0
12372.0,72,4,3,3,1.298040e+03,4,434,3.5
12373.0,311,1,1,1,3.646000e+02,2,112,1.5
12374.0,25,5,1,1,7.429300e+02,3,513,2.0
12375.0,3,5,3,3,4.554200e+02,2,532,2.5
12377.0,315,1,2,2,1.628120e+03,4,124,3.0
12378.0,130,3,1,1,4.008620e+03,5,315,3.0
12379.0,82,4,3,3,8.502900e+02,3,433,3.0
12380.0,22,5,5,4,2.720560e+03,5,545,4.5
12381.0,5,5,6,4,1.803960e+03,4,544,4.0
...,...,...,...,...,...,...,...,...
18241.0,10,5,18,5,2.058090e+03,5,555,5.0
18242.0,72,4,4,3,2.232490e+03,5,435,4.0
18245.0,7,5,8,5,2.507560e+03,5,555,5.0
18246.0,24,5,2,2,5.961000e+02,3,523,2.5
18248.0,114,3,4,3,7.830200e+02,3,333,3.0
18249.0,17,5,1,1,9.534000e+01,1,511,1.0
18250.0,301,1,2,2,3.429200e+02,2,122,2.0
18251.0,87,4,1,1,4.314720e+03,5,415,3.0
18252.0,51,4,2,2,5.266700e+02,3,423,2.5
18255.0,89,4,1,1,1.033000e+02,1,411,1.0
18257.0,39,4,12,5,2.265380e+03,5,455,5.0
18259.0,25,5,3,3,2.338600e+03,5,535,4.0
18260.0,173,2,8,5,2.595000e+03,5,255,5.0
18261.0,43,4,2,2,3.242400e+02,2,422,2.0
18262.0,140,3,1,1,1.494800e+02,1,311,1.0
18263.0,23,5,4,3,1.211080e+03,4,534,3.5
18265.0,72,4,2,2,8.015100e+02,3,423,2.5
18269.0,358,1,2,2,1.389000e+02,1,121,1.5
18270.0,38,4,3,3,2.389500e+02,1,431,2.0
18272.0,3,5,7,4,3.064780e+03,5,545,4.5
18273.0,2,5,3,3,2.040000e+02,1,531,2.0
18274.0,18,5,2,2,1.243450e-14,1,521,1.5
18276.0,21,5,3,3,3.233600e+02,2,532,2.5
18277.0,58,4,2,2,9.763000e+01,1,421,1.5
18278.0,74,4,1,1,1.739000e+02,1,411,1.0
18280.0,278,1,1,1,1.806000e+02,1,111,1.0
18281.0,181,2,1,1,8.082000e+01,1,211,1.0
18282.0,8,5,3,3,1.766000e+02,1,531,2.0
18283.0,4,5,16,5,2.094880e+03,5,555,5.0
18287.0,43,4,3,3,1.837280e+03,4,434,3.5

In [50]:
rfm1['rscore']=rfm1['rscore'].astype('int')

In [51]:
rmf

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,present date,difference,price
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,2011-12-10 12:50:00,374,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,2011-12-10 12:50:00,374,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,2011-12-10 12:50:00,374,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,2011-12-10 12:50:00,374,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,2011-12-10 12:50:00,374,20.34
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,2010-12-01 08:26:00,7.65,17850.0,United Kingdom,2011-12-10 12:50:00,374,15.30
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,2010-12-01 08:26:00,4.25,17850.0,United Kingdom,2011-12-10 12:50:00,374,25.50
7,536366,22633,HAND WARMER UNION JACK,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom,2011-12-10 12:50:00,374,11.10
8,536366,22632,HAND WARMER RED POLKA DOT,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom,2011-12-10 12:50:00,374,11.10
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,2010-12-01 08:34:00,1.69,13047.0,United Kingdom,2011-12-10 12:50:00,374,54.08
10,536367,22745,POPPY'S PLAYHOUSE BEDROOM,6,2010-12-01 08:34:00,2.10,13047.0,United Kingdom,2011-12-10 12:50:00,374,12.60
11,536367,22748,POPPY'S PLAYHOUSE KITCHEN,6,2010-12-01 08:34:00,2.10,13047.0,United Kingdom,2011-12-10 12:50:00,374,12.60
12,536367,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,8,2010-12-01 08:34:00,3.75,13047.0,United Kingdom,2011-12-10 12:50:00,374,30.00
13,536367,22310,IVORY KNITTED MUG COSY,6,2010-12-01 08:34:00,1.65,13047.0,United Kingdom,2011-12-10 12:50:00,374,9.90
14,536367,84969,BOX OF 6 ASSORTED COLOUR TEASPOONS,6,2010-12-01 08:34:00,4.25,13047.0,United Kingdom,2011-12-10 12:50:00,374,25.50
15,536367,22623,BOX OF VINTAGE JIGSAW BLOCKS,3,2010-12-01 08:34:00,4.95,13047.0,United Kingdom,2011-12-10 12:50:00,374,14.85
16,536367,22622,BOX OF VINTAGE ALPHABET BLOCKS,2,2010-12-01 08:34:00,9.95,13047.0,United Kingdom,2011-12-10 12:50:00,374,19.90
17,536367,21754,HOME BUILDING BLOCK WORD,3,2010-12-01 08:34:00,5.95,13047.0,United Kingdom,2011-12-10 12:50:00,374,17.85
18,536367,21755,LOVE BUILDING BLOCK WORD,3,2010-12-01 08:34:00,5.95,13047.0,United Kingdom,2011-12-10 12:50:00,374,17.85
19,536367,21777,RECIPE BOX WITH METAL HEART,4,2010-12-01 08:34:00,7.95,13047.0,United Kingdom,2011-12-10 12:50:00,374,31.80
20,536367,48187,DOORMAT NEW ENGLAND,4,2010-12-01 08:34:00,7.95,13047.0,United Kingdom,2011-12-10 12:50:00,374,31.80
21,536368,22960,JAM MAKING SET WITH JARS,6,2010-12-01 08:34:00,4.25,13047.0,United Kingdom,2011-12-10 12:50:00,374,25.50
22,536368,22913,RED COAT RACK PARIS FASHION,3,2010-12-01 08:34:00,4.95,13047.0,United Kingdom,2011-12-10 12:50:00,374,14.85
23,536368,22912,YELLOW COAT RACK PARIS FASHION,3,2010-12-01 08:34:00,4.95,13047.0,United Kingdom,2011-12-10 12:50:00,374,14.85
24,536368,22914,BLUE COAT RACK PARIS FASHION,3,2010-12-01 08:34:00,4.95,13047.0,United Kingdom,2011-12-10 12:50:00,374,14.85
25,536369,21756,BATH BUILDING BLOCK WORD,3,2010-12-01 08:35:00,5.95,13047.0,United Kingdom,2011-12-10 12:50:00,374,17.85
26,536370,22728,ALARM CLOCK BAKELIKE PINK,24,2010-12-01 08:45:00,3.75,12583.0,France,2011-12-10 12:50:00,374,90.00
27,536370,22727,ALARM CLOCK BAKELIKE RED,24,2010-12-01 08:45:00,3.75,12583.0,France,2011-12-10 12:50:00,374,90.00
28,536370,22726,ALARM CLOCK BAKELIKE GREEN,12,2010-12-01 08:45:00,3.75,12583.0,France,2011-12-10 12:50:00,374,45.00
29,536370,21724,PANDA AND BUNNIES STICKER SHEET,12,2010-12-01 08:45:00,0.85,12583.0,France,2011-12-10 12:50:00,374,10.20
...,...,...,...,...,...,...,...,...,...,...,...
541879,581585,22726,ALARM CLOCK BAKELIKE GREEN,8,2011-12-09 12:31:00,3.75,15804.0,United Kingdom,2011-12-10 12:50:00,1,30.00
541880,581585,22727,ALARM CLOCK BAKELIKE RED,4,2011-12-09 12:31:00,3.75,15804.0,United Kingdom,2011-12-10 12:50:00,1,15.00
541881,581585,16016,LARGE CHINESE STYLE SCISSOR,10,2011-12-09 12:31:00,0.85,15804.0,United Kingdom,2011-12-10 12:50:00,1,8.50
541882,581585,21916,SET 12 RETRO WHITE CHALK STICKS,24,2011-12-09 12:31:00,0.42,15804.0,United Kingdom,2011-12-10 12:50:00,1,10.08
541883,581585,84692,BOX OF 24 COCKTAIL PARASOLS,25,2011-12-09 12:31:00,0.42,15804.0,United Kingdom,2011-12-10 12:50:00,1,10.50
541884,581585,84946,ANTIQUE SILVER T-LIGHT GLASS,12,2011-12-09 12:31:00,1.25,15804.0,United Kingdom,2011-12-10 12:50:00,1,15.00
541885,581585,21684,SMALL MEDINA STAMPED METAL BOWL,12,2011-12-09 12:31:00,0.85,15804.0,United Kingdom,2011-12-10 12:50:00,1,10.20
541886,581585,22398,MAGNETS PACK OF 4 SWALLOWS,12,2011-12-09 12:31:00,0.39,15804.0,United Kingdom,2011-12-10 12:50:00,1,4.68
541887,581585,23328,SET 6 SCHOOL MILK BOTTLES IN CRATE,4,2011-12-09 12:31:00,3.75,15804.0,United Kingdom,2011-12-10 12:50:00,1,15.00
541888,581585,23145,ZINC T-LIGHT HOLDER STAR LARGE,12,2011-12-09 12:31:00,0.95,15804.0,United Kingdom,2011-12-10 12:50:00,1,11.40
541889,581585,22466,FAIRY TALE COTTAGE NIGHT LIGHT,12,2011-12-09 12:31:00,1.95,15804.0,United Kingdom,2011-12-10 12:50:00,1,23.40
541890,581586,22061,LARGE CAKE STAND HANGING STRAWBERY,8,2011-12-09 12:49:00,2.95,13113.0,United Kingdom,2011-12-10 12:50:00,1,23.60
541891,581586,23275,SET OF 3 HANGING OWLS OLLIE BEAK,24,2011-12-09 12:49:00,1.25,13113.0,United Kingdom,2011-12-10 12:50:00,1,30.00
541892,581586,21217,RED RETROSPOT ROUND CAKE TINS,24,2011-12-09 12:49:00,8.95,13113.0,United Kingdom,2011-12-10 12:50:00,1,214.80
541893,581586,20685,DOORMAT RED RETROSPOT,10,2011-12-09 12:49:00,7.08,13113.0,United Kingdom,2011-12-10 12:50:00,1,70.80
541894,581587,22631,CIRCUS PARADE LUNCH BOX,12,2011-12-09 12:50:00,1.95,12680.0,France,2011-12-10 12:50:00,1,23.40
541895,581587,22556,PLASTERS IN TIN CIRCUS PARADE,12,2011-12-09 12:50:00,1.65,12680.0,France,2011-12-10 12:50:00,1,19.80
541896,581587,22555,PLASTERS IN TIN STRONGMAN,12,2011-12-09 12:50:00,1.65,12680.0,France,2011-12-10 12:50:00,1,19.80
541897,581587,22728,ALARM CLOCK BAKELIKE PINK,4,2011-12-09 12:50:00,3.75,12680.0,France,2011-12-10 12:50:00,1,15.00
541898,581587,22727,ALARM CLOCK BAKELIKE RED,4,2011-12-09 12:50:00,3.75,12680.0,France,2011-12-10 12:50:00,1,15.00
541899,581587,22726,ALARM CLOCK BAKELIKE GREEN,4,2011-12-09 12:50:00,3.75,12680.0,France,2011-12-10 12:50:00,1,15.00
541900,581587,22730,ALARM CLOCK BAKELIKE IVORY,4,2011-12-09 12:50:00,3.75,12680.0,France,2011-12-10 12:50:00,1,15.00
541901,581587,22367,CHILDRENS APRON SPACEBOY DESIGN,8,2011-12-09 12:50:00,1.95,12680.0,France,2011-12-10 12:50:00,1,15.60
541902,581587,22629,SPACEBOY LUNCH BOX,12,2011-12-09 12:50:00,1.95,12680.0,France,2011-12-10 12:50:00,1,23.40
541903,581587,23256,CHILDRENS CUTLERY SPACEBOY,4,2011-12-09 12:50:00,4.15,12680.0,France,2011-12-10 12:50:00,1,16.60
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France,2011-12-10 12:50:00,1,10.20
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France,2011-12-10 12:50:00,1,12.60
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France,2011-12-10 12:50:00,1,16.60
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France,2011-12-10 12:50:00,1,16.60
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France,2011-12-10 12:50:00,1,14.85

In [52]:
c=rmf[['CustomerID','Country']]
c=c.set_index('CustomerID')
c

                   Country
CustomerID
17850.0     United Kingdom
17850.0     United Kingdom
17850.0     United Kingdom
17850.0     United Kingdom
17850.0     United Kingdom
17850.0     United Kingdom
17850.0     United Kingdom
17850.0     United Kingdom
17850.0     United Kingdom
13047.0     United Kingdom
13047.0     United Kingdom
13047.0     United Kingdom
13047.0     United Kingdom
13047.0     United Kingdom
13047.0     United Kingdom
13047.0     United Kingdom
13047.0     United Kingdom
13047.0     United Kingdom
13047.0     United Kingdom
13047.0     United Kingdom
13047.0     United Kingdom
13047.0     United Kingdom
13047.0     United Kingdom
13047.0     United Kingdom
13047.0     United Kingdom
13047.0     United Kingdom
12583.0             France
12583.0             France
12583.0             France
12583.0             France
...                    ...
15804.0     United Kingdom
15804.0     United Kingdom
15804.0     United Kingdom
15804.0     United Kingdom
15804.0     United Kingdom
15804.0     United Kingdom
15804.0     United Kingdom
15804.0     United Kingdom
15804.0     United Kingdom
15804.0     United Kingdom
15804.0     United Kingdom
13113.0     United Kingdom
13113.0     United Kingdom
13113.0     United Kingdom
13113.0     United Kingdom
12680.0             France
12680.0             France
12680.0             France
12680.0             France
12680.0             France
12680.0             France
12680.0             France
12680.0             France
12680.0             France
12680.0             France
12680.0             France
12680.0             France
12680.0             France
12680.0             France
12680.0             France

[541909 rows x 1 columns]

In [53]:
rfm=pd.merge(rfm1,c,on='CustomerID')
rfm=rfm.reset_index()
rfm

,CustomerID,recency,rscore,frequency,fscore,monetory,mscore,rfmscore,fmscore,Country
0,12347.0,2,5,7,4,4310.00,5,545,4.5,Iceland
1,12347.0,2,5,7,4,4310.00,5,545,4.5,Iceland
2,12347.0,2,5,7,4,4310.00,5,545,4.5,Iceland
3,12347.0,2,5,7,4,4310.00,5,545,4.5,Iceland
4,12347.0,2,5,7,4,4310.00,5,545,4.5,Iceland
5,12347.0,2,5,7,4,4310.00,5,545,4.5,Iceland
6,12347.0,2,5,7,4,4310.00,5,545,4.5,Iceland
7,12347.0,2,5,7,4,4310.00,5,545,4.5,Iceland
8,12347.0,2,5,7,4,4310.00,5,545,4.5,Iceland
9,12347.0,2,5,7,4,4310.00,5,545,4.5,Iceland
10,12347.0,2,5,7,4,4310.00,5,545,4.5,Iceland
11,12347.0,2,5,7,4,4310.00,5,545,4.5,Iceland
12,12347.0,2,5,7,4,4310.00,5,545,4.5,Iceland
13,12347.0,2,5,7,4,4310.00,5,545,4.5,Iceland
14,12347.0,2,5,7,4,4310.00,5,545,4.5,Iceland
15,12347.0,2,5,7,4,4310.00,5,545,4.5,Iceland
16,12347.0,2,5,7,4,4310.00,5,545,4.5,Iceland
17,12347.0,2,5,7,4,4310.00,5,545,4.5,Iceland
18,12347.0,2,5,7,4,4310.00,5,545,4.5,Iceland
19,12347.0,2,5,7,4,4310.00,5,545,4.5,Iceland
20,12347.0,2,5,7,4,4310.00,5,545,4.5,Iceland
21,12347.0,2,5,7,4,4310.00,5,545,4.5,Iceland
22,12347.0,2,5,7,4,4310.00,5,545,4.5,Iceland
23,12347.0,2,5,7,4,4310.00,5,545,4.5,Iceland
24,12347.0,2,5,7,4,4310.00,5,545,4.5,Iceland
25,12347.0,2,5,7,4,4310.00,5,545,4.5,Iceland
26,12347.0,2,5,7,4,4310.00,5,545,4.5,Iceland
27,12347.0,2,5,7,4,4310.00,5,545,4.5,Iceland
28,12347.0,2,5,7,4,4310.00,5,545,4.5,Iceland
29,12347.0,2,5,7,4,4310.00,5,545,4.5,Iceland
...,...,...,...,...,...,...,...,...,...,...
406486,18287.0,43,4,3,3,1837.28,4,434,3.5,United Kingdom
406487,18287.0,43,4,3,3,1837.28,4,434,3.5,United Kingdom
406488,18287.0,43,4,3,3,1837.28,4,434,3.5,United Kingdom
406489,18287.0,43,4,3,3,1837.28,4,434,3.5,United Kingdom
406490,18287.0,43,4,3,3,1837.28,4,434,3.5,United Kingdom
406491,18287.0,43,4,3,3,1837.28,4,434,3.5,United Kingdom
406492,18287.0,43,4,3,3,1837.28,4,434,3.5,United Kingdom
406493,18287.0,43,4,3,3,1837.28,4,434,3.5,United Kingdom
406494,18287.0,43,4,3,3,1837.28,4,434,3.5,United Kingdom
406495,18287.0,43,4,3,3,1837.28,4,434,3.5,United Kingdom
406496,18287.0,43,4,3,3,1837.28,4,434,3.5,United Kingdom
406497,18287.0,43,4,3,3,1837.28,4,434,3.5,United Kingdom
406498,18287.0,43,4,3,3,1837.28,4,434,3.5,United Kingdom
406499,18287.0,43,4,3,3,1837.28,4,434,3.5,United Kingdom
406500,18287.0,43,4,3,3,1837.28,4,434,3.5,United Kingdom
406501,18287.0,43,4,3,3,1837.28,4,434,3.5,United Kingdom
406502,18287.0,43,4,3,3,1837.28,4,434,3.5,United Kingdom
406503,18287.0,43,4,3,3,1837.28,4,434,3.5,United Kingdom
406504,18287.0,43,4,3,3,1837.28,4,434,3.5,United Kingdom
406505,18287.0,43,4,3,3,1837.28,4,434,3.5,United Kingdom
406506,18287.0,43,4,3,3,1837.28,4,434,3.5,United Kingdom
406507,18287.0,43,4,3,3,1837.28,4,434,3.5,United Kingdom
406508,18287.0,43,4,3,3,1837.28,4,434,3.5,United Kingdom
406509,18287.0,43,4,3,3,1837.28,4,434,3.5,United Kingdom
406510,18287.0,43,4,3,3,1837.28,4,434,3.5,United Kingdom
406511,18287.0,43,4,3,3,1837.28,4,434,3.5,United Kingdom
406512,18287.0,43,4,3,3,1837.28,4,434,3.5,United Kingdom
406513,18287.0,43,4,3,3,1837.28,4,434,3.5,United Kingdom
406514,18287.0,43,4,3,3,1837.28,4,434,3.5,United Kingdom
406515,18287.0,43,4,3,3,1837.28,4,434,3.5,United Kingdom

In [54]:
rfm.loc[rfm['CustomerID']==12348]

,CustomerID,recency,rscore,frequency,fscore,monetory,mscore,rfmscore,fmscore,Country
182,12348.0,75,4,4,3,1797.24,4,434,3.5,Finland
183,12348.0,75,4,4,3,1797.24,4,434,3.5,Finland
184,12348.0,75,4,4,3,1797.24,4,434,3.5,Finland
185,12348.0,75,4,4,3,1797.24,4,434,3.5,Finland
186,12348.0,75,4,4,3,1797.24,4,434,3.5,Finland
187,12348.0,75,4,4,3,1797.24,4,434,3.5,Finland
188,12348.0,75,4,4,3,1797.24,4,434,3.5,Finland
189,12348.0,75,4,4,3,1797.24,4,434,3.5,Finland
190,12348.0,75,4,4,3,1797.24,4,434,3.5,Finland
191,12348.0,75,4,4,3,1797.24,4,434,3.5,Finland
192,12348.0,75,4,4,3,1797.24,4,434,3.5,Finland
193,12348.0,75,4,4,3,1797.24,4,434,3.5,Finland
194,12348.0,75,4,4,3,1797.24,4,434,3.5,Finland
195,12348.0,75,4,4,3,1797.24,4,434,3.5,Finland
196,12348.0,75,4,4,3,1797.24,4,434,3.5,Finland
197,12348.0,75,4,4,3,1797.24,4,434,3.5,Finland
198,12348.0,75,4,4,3,1797.24,4,434,3.5,Finland
199,12348.0,75,4,4,3,1797.24,4,434,3.5,Finland
200,12348.0,75,4,4,3,1797.24,4,434,3.5,Finland
201,12348.0,75,4,4,3,1797.24,4,434,3.5,Finland
202,12348.0,75,4,4,3,1797.24,4,434,3.5,Finland
203,12348.0,75,4,4,3,1797.24,4,434,3.5,Finland
204,12348.0,75,4,4,3,1797.24,4,434,3.5,Finland
205,12348.0,75,4,4,3,1797.24,4,434,3.5,Finland
206,12348.0,75,4,4,3,1797.24,4,434,3.5,Finland
207,12348.0,75,4,4,3,1797.24,4,434,3.5,Finland
208,12348.0,75,4,4,3,1797.24,4,434,3.5,Finland
209,12348.0,75,4,4,3,1797.24,4,434,3.5,Finland
210,12348.0,75,4,4,3,1797.24,4,434,3.5,Finland
211,12348.0,75,4,4,3,1797.24,4,434,3.5,Finland
212,12348.0,75,4,4,3,1797.24,4,434,3.5,Finland

In [55]:
rfm=rfm.drop_duplicates(subset=['CustomerID','Country'],keep='first')
rfm

,CustomerID,recency,rscore,frequency,fscore,monetory,mscore,rfmscore,fmscore,Country
0,12347.0,2,5,7,4,4.310000e+03,5,545,4.5,Iceland
182,12348.0,75,4,4,3,1.797240e+03,4,434,3.5,Finland
213,12349.0,19,5,1,1,1.757550e+03,4,514,2.5,Italy
286,12350.0,310,1,1,1,3.344000e+02,2,112,1.5,Norway
303,12352.0,36,4,11,5,1.545410e+03,4,454,4.5,Norway
398,12353.0,204,2,1,1,8.900000e+01,1,211,1.0,Bahrain
402,12354.0,232,1,1,1,1.079400e+03,4,114,2.5,Spain
460,12355.0,214,2,1,1,4.594000e+02,2,212,1.5,Bahrain
473,12356.0,23,5,3,3,2.811430e+03,5,535,4.0,Portugal
532,12357.0,33,4,1,1,6.207670e+03,5,415,3.0,Switzerland
663,12358.0,2,5,2,2,1.168060e+03,4,524,3.0,Austria
682,12359.0,8,5,6,4,6.245530e+03,5,545,4.5,Cyprus
936,12360.0,52,4,3,3,2.662060e+03,5,435,4.0,Austria
1065,12361.0,287,1,1,1,1.899000e+02,1,111,1.0,Belgium
1075,12362.0,3,5,13,5,5.154580e+03,5,555,5.0,Belgium
1349,12363.0,110,3,2,2,5.520000e+02,3,323,2.5,Unspecified
1372,12364.0,8,5,4,3,1.313100e+03,4,534,3.5,Belgium
1457,12365.0,291,1,3,3,3.206900e+02,2,132,2.5,Cyprus
1480,12367.0,4,5,1,1,1.689000e+02,1,511,1.0,Denmark
1491,12370.0,51,4,4,3,3.545690e+03,5,435,4.0,Cyprus
1574,12370.0,51,4,4,3,3.545690e+03,5,435,4.0,Austria
1658,12371.0,45,4,2,2,1.887960e+03,4,424,3.0,Switzerland
1721,12372.0,72,4,3,3,1.298040e+03,4,434,3.5,Denmark
1773,12373.0,311,1,1,1,3.646000e+02,2,112,1.5,Austria
1787,12374.0,25,5,1,1,7.429300e+02,3,513,2.0,Austria
1820,12375.0,3,5,3,3,4.554200e+02,2,532,2.5,Finland
1838,12377.0,315,1,2,2,1.628120e+03,4,124,3.0,Switzerland
1915,12378.0,130,3,1,1,4.008620e+03,5,315,3.0,Switzerland
2134,12379.0,82,4,3,3,8.502900e+02,3,433,3.0,Belgium
2175,12380.0,22,5,5,4,2.720560e+03,5,545,4.5,Belgium
...,...,...,...,...,...,...,...,...,...,...
404400,18241.0,10,5,18,5,2.058090e+03,5,555,5.0,United Kingdom
404505,18242.0,72,4,4,3,2.232490e+03,5,435,4.0,United Kingdom
404583,18245.0,7,5,8,5,2.507560e+03,5,555,5.0,United Kingdom
404760,18246.0,24,5,2,2,5.961000e+02,3,523,2.5,United Kingdom
404764,18248.0,114,3,4,3,7.830200e+02,3,333,3.0,United Kingdom
404813,18249.0,17,5,1,1,9.534000e+01,1,511,1.0,United Kingdom
404821,18250.0,301,1,2,2,3.429200e+02,2,122,2.0,United Kingdom
404843,18251.0,87,4,1,1,4.314720e+03,5,415,3.0,United Kingdom
404859,18252.0,51,4,2,2,5.266700e+02,3,423,2.5,United Kingdom
404957,18255.0,89,4,1,1,1.033000e+02,1,411,1.0,United Kingdom
404963,18257.0,39,4,12,5,2.265380e+03,5,455,5.0,United Kingdom
405086,18259.0,25,5,3,3,2.338600e+03,5,535,4.0,United Kingdom
405128,18260.0,173,2,8,5,2.595000e+03,5,255,5.0,United Kingdom
405268,18261.0,43,4,2,2,3.242400e+02,2,422,2.0,United Kingdom
405289,18262.0,140,3,1,1,1.494800e+02,1,311,1.0,United Kingdom
405302,18263.0,23,5,4,3,1.211080e+03,4,534,3.5,United Kingdom
405364,18265.0,72,4,2,2,8.015100e+02,3,423,2.5,United Kingdom
405410,18269.0,358,1,2,2,1.389000e+02,1,121,1.5,United Kingdom
405418,18270.0,38,4,3,3,2.389500e+02,1,431,2.0,United Kingdom
405431,18272.0,3,5,7,4,3.064780e+03,5,545,4.5,United Kingdom
405601,18273.0,2,5,3,3,2.040000e+02,1,531,2.0,United Kingdom
405604,18274.0,18,5,2,2,1.243450e-14,1,521,1.5,United Kingdom
405626,18276.0,21,5,3,3,3.233600e+02,2,532,2.5,United Kingdom
405642,18277.0,58,4,2,2,9.763000e+01,1,421,1.5,United Kingdom
405651,18278.0,74,4,1,1,1.739000e+02,1,411,1.0,United Kingdom
405660,18280.0,278,1,1,1,1.806000e+02,1,111,1.0,United Kingdom
405670,18281.0,181,2,1,1,8.082000e+01,1,211,1.0,United Kingdom
405677,18282.0,8,5,3,3,1.766000e+02,1,531,2.0,United Kingdom
405690,18283.0,4,5,16,5,2.094880e+03,5,555,5.0,United Kingdom
406446,18287.0,43,4,3,3,1.837280e+03,4,434,3.5,United Kingdom

In [56]:
newrfm=pd.DataFrame(columns=['CustomerID','recency','rscore','frequency','fscore','monetory','mscore','rfmscore','fmscore','Country','segmentation'])
newrfm

Empty DataFrame
Columns: [CustomerID, recency, rscore, frequency, fscore, monetory, mscore, rfmscore, fmscore, Country, segmentation]
Index: []

In [57]:
import numpy as np

In [58]:
def segment(x):
    global newrfm
    if (x['rscore']in range (4,6)) & (x['fmscore'] in np.arange(4,5.5,0.5)):
        x['segmentation']='champion'
        df1=pd.DataFrame([[x['CustomerID'],x['recency'],x['rscore'],x['frequency'],x['fscore'],x['monetory'],x['mscore'],x['rfmscore'],x['fmscore'],x['Country'],x['segmentation']]],columns=['CustomerID','recency','rscore','frequency','fscore','monetory','mscore','rfmscore','fmscore','Country','segmentation'])
        newrfm=newrfm.append(df1)
    if  (x['rscore']in range (2,6)) & (x['fmscore'] in np.arange(3,5.5,0.5)):
        x['segmentation']='loyal customer'
        df1=pd.DataFrame([[x['CustomerID'],x['recency'],x['rscore'],x['frequency'],x['fscore'],x['monetory'],x['mscore'],x['rfmscore'],x['fmscore'],x['Country'],x['segmentation']]],columns=['CustomerID','recency','rscore','frequency','fscore','monetory','mscore','rfmscore','fmscore','Country','segmentation'])
        newrfm=newrfm.append(df1) 
    if  (x['rscore']in range (3,6)) & (x['fmscore'] in np.arange(1,3.5,0.5)):
        x['segmentation']='Potential Loyalist'
        df1=pd.DataFrame([[x['CustomerID'],x['recency'],x['rscore'],x['frequency'],x['fscore'],x['monetory'],x['mscore'],x['rfmscore'],x['fmscore'],x['Country'],x['segmentation']]],columns=['CustomerID','recency','rscore','frequency','fscore','monetory','mscore','rfmscore','fmscore','Country','segmentation'])
        newrfm=newrfm.append(df1)
    if  (x['rscore']in range (4,6)) & (x['fmscore'] in np.arange(1,1.5,0.5)):
        x['segmentation']='Recent Customers'
        df1=pd.DataFrame([[x['CustomerID'],x['recency'],x['rscore'],x['frequency'],x['fscore'],x['monetory'],x['mscore'],x['rfmscore'],x['fmscore'],x['Country'],x['segmentation']]],columns=['CustomerID','recency','rscore','frequency','fscore','monetory','mscore','rfmscore','fmscore','Country','segmentation'])
        newrfm=newrfm.append(df1) 
    if  (x['rscore']in range (3,5)) & (x['fmscore'] in np.arange(1,1.5,0.5)):
        x['segmentation']='Promising'
        df1=pd.DataFrame([[x['CustomerID'],x['recency'],x['rscore'],x['frequency'],x['fscore'],x['monetory'],x['mscore'],x['rfmscore'],x['fmscore'],x['Country'],x['segmentation']]],columns=['CustomerID','recency','rscore','frequency','fscore','monetory','mscore','rfmscore','fmscore','Country','segmentation'])
        newrfm=newrfm.append(df1)
    if  (x['rscore']in range (2,4)) & (x['fmscore'] in np.arange(2,3.5,0.5)):
        x['segmentation']='Customers Needing Attention'
        df1=pd.DataFrame([[x['CustomerID'],x['recency'],x['rscore'],x['frequency'],x['fscore'],x['monetory'],x['mscore'],x['rfmscore'],x['fmscore'],x['Country'],x['segmentation']]],columns=['CustomerID','recency','rscore','frequency','fscore','monetory','mscore','rfmscore','fmscore','Country','segmentation'])
        newrfm=newrfm.append(df1)
    if  (x['rscore']in range (2,4)) & (x['fmscore'] in np.arange(1,2.5,0.5)):
        x['segmentation']='About To Sleep'
        df1=pd.DataFrame([[x['CustomerID'],x['recency'],x['rscore'],x['frequency'],x['fscore'],x['monetory'],x['mscore'],x['rfmscore'],x['fmscore'],x['Country'],x['segmentation']]],columns=['CustomerID','recency','rscore','frequency','fscore','monetory','mscore','rfmscore','fmscore','Country','segmentation'])
        newrfm=newrfm.append(df1)
    if  (x['rscore']in range (0,3)) & (x['fmscore'] in np.arange(2,5.5,0.5)):
        x['segmentation']='At Risk'
        df1=pd.DataFrame([[x['CustomerID'],x['recency'],x['rscore'],x['frequency'],x['fscore'],x['monetory'],x['mscore'],x['rfmscore'],x['fmscore'],x['Country'],x['segmentation']]],columns=['CustomerID','recency','rscore','frequency','fscore','monetory','mscore','rfmscore','fmscore','Country','segmentation'])
        newrfm=newrfm.append(df1)
    if  (x['rscore']in range (0,2)) & (x['fmscore'] in np.arange(4,5.5,0.5)):
        x['segmentation']='Can’t Lose Them'
        df1=pd.DataFrame([[x['CustomerID'],x['recency'],x['rscore'],x['frequency'],x['fscore'],x['monetory'],x['mscore'],x['rfmscore'],x['fmscore'],x['Country'],x['segmentation']]],columns=['CustomerID','recency','rscore','frequency','fscore','monetory','mscore','rfmscore','fmscore','Country','segmentation'])
        newrfm=newrfm.append(df1)
    if  (x['rscore']in range (1,3)) & (x['fmscore'] in np.arange(1,2.5,0.5)):
        x['segmentation']='Hibernating'
        df1=pd.DataFrame([[x['CustomerID'],x['recency'],x['rscore'],x['frequency'],x['fscore'],x['monetory'],x['mscore'],x['rfmscore'],x['fmscore'],x['Country'],x['segmentation']]],columns=['CustomerID','recency','rscore','frequency','fscore','monetory','mscore','rfmscore','fmscore','Country','segmentation'])
        newrfm=newrfm.append(df1)
    if  (x['rscore']in range (0,3)) & (x['fmscore'] in np.arange(1,2.5,0.5)):
        x['segmentation']='Lost'
        df1=pd.DataFrame([[x['CustomerID'],x['recency'],x['rscore'],x['frequency'],x['fscore'],x['monetory'],x['mscore'],x['rfmscore'],x['fmscore'],x['Country'],x['segmentation']]],columns=['CustomerID','recency','rscore','frequency','fscore','monetory','mscore','rfmscore','fmscore','Country','segmentation'])
        newrfm=newrfm.append(df1)

In [59]:
df=rfm.copy()
df['segmentation']=''
df

,CustomerID,recency,rscore,frequency,fscore,monetory,mscore,rfmscore,fmscore,Country,segmentation
0,12347.0,2,5,7,4,4.310000e+03,5,545,4.5,Iceland,
182,12348.0,75,4,4,3,1.797240e+03,4,434,3.5,Finland,
213,12349.0,19,5,1,1,1.757550e+03,4,514,2.5,Italy,
286,12350.0,310,1,1,1,3.344000e+02,2,112,1.5,Norway,
303,12352.0,36,4,11,5,1.545410e+03,4,454,4.5,Norway,
398,12353.0,204,2,1,1,8.900000e+01,1,211,1.0,Bahrain,
402,12354.0,232,1,1,1,1.079400e+03,4,114,2.5,Spain,
460,12355.0,214,2,1,1,4.594000e+02,2,212,1.5,Bahrain,
473,12356.0,23,5,3,3,2.811430e+03,5,535,4.0,Portugal,
532,12357.0,33,4,1,1,6.207670e+03,5,415,3.0,Switzerland,
663,12358.0,2,5,2,2,1.168060e+03,4,524,3.0,Austria,
682,12359.0,8,5,6,4,6.245530e+03,5,545,4.5,Cyprus,
936,12360.0,52,4,3,3,2.662060e+03,5,435,4.0,Austria,
1065,12361.0,287,1,1,1,1.899000e+02,1,111,1.0,Belgium,
1075,12362.0,3,5,13,5,5.154580e+03,5,555,5.0,Belgium,
1349,12363.0,110,3,2,2,5.520000e+02,3,323,2.5,Unspecified,
1372,12364.0,8,5,4,3,1.313100e+03,4,534,3.5,Belgium,
1457,12365.0,291,1,3,3,3.206900e+02,2,132,2.5,Cyprus,
1480,12367.0,4,5,1,1,1.689000e+02,1,511,1.0,Denmark,
1491,12370.0,51,4,4,3,3.545690e+03,5,435,4.0,Cyprus,
1574,12370.0,51,4,4,3,3.545690e+03,5,435,4.0,Austria,
1658,12371.0,45,4,2,2,1.887960e+03,4,424,3.0,Switzerland,
1721,12372.0,72,4,3,3,1.298040e+03,4,434,3.5,Denmark,
1773,12373.0,311,1,1,1,3.646000e+02,2,112,1.5,Austria,
1787,12374.0,25,5,1,1,7.429300e+02,3,513,2.0,Austria,
1820,12375.0,3,5,3,3,4.554200e+02,2,532,2.5,Finland,
1838,12377.0,315,1,2,2,1.628120e+03,4,124,3.0,Switzerland,
1915,12378.0,130,3,1,1,4.008620e+03,5,315,3.0,Switzerland,
2134,12379.0,82,4,3,3,8.502900e+02,3,433,3.0,Belgium,
2175,12380.0,22,5,5,4,2.720560e+03,5,545,4.5,Belgium,
...,...,...,...,...,...,...,...,...,...,...,...
404400,18241.0,10,5,18,5,2.058090e+03,5,555,5.0,United Kingdom,
404505,18242.0,72,4,4,3,2.232490e+03,5,435,4.0,United Kingdom,
404583,18245.0,7,5,8,5,2.507560e+03,5,555,5.0,United Kingdom,
404760,18246.0,24,5,2,2,5.961000e+02,3,523,2.5,United Kingdom,
404764,18248.0,114,3,4,3,7.830200e+02,3,333,3.0,United Kingdom,
404813,18249.0,17,5,1,1,9.534000e+01,1,511,1.0,United Kingdom,
404821,18250.0,301,1,2,2,3.429200e+02,2,122,2.0,United Kingdom,
404843,18251.0,87,4,1,1,4.314720e+03,5,415,3.0,United Kingdom,
404859,18252.0,51,4,2,2,5.266700e+02,3,423,2.5,United Kingdom,
404957,18255.0,89,4,1,1,1.033000e+02,1,411,1.0,United Kingdom,
404963,18257.0,39,4,12,5,2.265380e+03,5,455,5.0,United Kingdom,
405086,18259.0,25,5,3,3,2.338600e+03,5,535,4.0,United Kingdom,
405128,18260.0,173,2,8,5,2.595000e+03,5,255,5.0,United Kingdom,
405268,18261.0,43,4,2,2,3.242400e+02,2,422,2.0,United Kingdom,
405289,18262.0,140,3,1,1,1.494800e+02,1,311,1.0,United Kingdom,
405302,18263.0,23,5,4,3,1.211080e+03,4,534,3.5,United Kingdom,
405364,18265.0,72,4,2,2,8.015100e+02,3,423,2.5,United Kingdom,
405410,18269.0,358,1,2,2,1.389000e+02,1,121,1.5,United Kingdom,
405418,18270.0,38,4,3,3,2.389500e+02,1,431,2.0,United Kingdom,
405431,18272.0,3,5,7,4,3.064780e+03,5,545,4.5,United Kingdom,
405601,18273.0,2,5,3,3,2.040000e+02,1,531,2.0,United Kingdom,
405604,18274.0,18,5,2,2,1.243450e-14,1,521,1.5,United Kingdom,
405626,18276.0,21,5,3,3,3.233600e+02,2,532,2.5,United Kingdom,
405642,18277.0,58,4,2,2,9.763000e+01,1,421,1.5,United Kingdom,
405651,18278.0,74,4,1,1,1.739000e+02,1,411,1.0,United Kingdom,
405660,18280.0,278,1,1,1,1.806000e+02,1,111,1.0,United Kingdom,
405670,18281.0,181,2,1,1,8.082000e+01,1,211,1.0,United Kingdom,
405677,18282.0,8,5,3,3,1.766000e+02,1,531,2.0,United Kingdom,
405690,18283.0,4,5,16,5,2.094880e+03,5,555,5.0,United Kingdom,
406446,18287.0,43,4,3,3,1.837280e+03,4,434,3.5,United Kingdom,

In [60]:
df.apply(segment,axis=1)

0         None
182       None
213       None
286       None
303       None
398       None
402       None
460       None
473       None
532       None
663       None
682       None
936       None
1065      None
1075      None
1349      None
1372      None
1457      None
1480      None
1491      None
1574      None
1658      None
1721      None
1773      None
1787      None
1820      None
1838      None
1915      None
2134      None
2175      None
          ...
404400    None
404505    None
404583    None
404760    None
404764    None
404813    None
404821    None
404843    None
404859    None
404957    None
404963    None
405086    None
405128    None
405268    None
405289    None
405302    None
405364    None
405410    None
405418    None
405431    None
405601    None
405604    None
405626    None
405642    None
405651    None
405660    None
405670    None
405677    None
405690    None
406446    None
Length: 4330, dtype: object

In [61]:
newrfm.drop_duplicates(subset=['CustomerID','segmentation'],keep='first',inplace=True)
newrfm

,CustomerID,recency,rscore,frequency,fscore,monetory,mscore,rfmscore,fmscore,Country,segmentation
0,12347.0,2,5,7,4,4.310000e+03,5,545,4.5,Iceland,champion
0,12347.0,2,5,7,4,4.310000e+03,5,545,4.5,Iceland,loyal customer
0,12348.0,75,4,4,3,1.797240e+03,4,434,3.5,Finland,loyal customer
0,12349.0,19,5,1,1,1.757550e+03,4,514,2.5,Italy,Potential Loyalist
0,12350.0,310,1,1,1,3.344000e+02,2,112,1.5,Norway,Hibernating
0,12350.0,310,1,1,1,3.344000e+02,2,112,1.5,Norway,Lost
0,12352.0,36,4,11,5,1.545410e+03,4,454,4.5,Norway,champion
0,12352.0,36,4,11,5,1.545410e+03,4,454,4.5,Norway,loyal customer
0,12353.0,204,2,1,1,8.900000e+01,1,211,1.0,Bahrain,About To Sleep
0,12353.0,204,2,1,1,8.900000e+01,1,211,1.0,Bahrain,Hibernating
0,12353.0,204,2,1,1,8.900000e+01,1,211,1.0,Bahrain,Lost
0,12354.0,232,1,1,1,1.079400e+03,4,114,2.5,Spain,At Risk
0,12355.0,214,2,1,1,4.594000e+02,2,212,1.5,Bahrain,About To Sleep
0,12355.0,214,2,1,1,4.594000e+02,2,212,1.5,Bahrain,Hibernating
0,12355.0,214,2,1,1,4.594000e+02,2,212,1.5,Bahrain,Lost
0,12356.0,23,5,3,3,2.811430e+03,5,535,4.0,Portugal,champion
0,12356.0,23,5,3,3,2.811430e+03,5,535,4.0,Portugal,loyal customer
0,12357.0,33,4,1,1,6.207670e+03,5,415,3.0,Switzerland,loyal customer
0,12357.0,33,4,1,1,6.207670e+03,5,415,3.0,Switzerland,Potential Loyalist
0,12358.0,2,5,2,2,1.168060e+03,4,524,3.0,Austria,loyal customer
0,12358.0,2,5,2,2,1.168060e+03,4,524,3.0,Austria,Potential Loyalist
0,12359.0,8,5,6,4,6.245530e+03,5,545,4.5,Cyprus,champion
0,12359.0,8,5,6,4,6.245530e+03,5,545,4.5,Cyprus,loyal customer
0,12360.0,52,4,3,3,2.662060e+03,5,435,4.0,Austria,champion
0,12360.0,52,4,3,3,2.662060e+03,5,435,4.0,Austria,loyal customer
0,12361.0,287,1,1,1,1.899000e+02,1,111,1.0,Belgium,Hibernating
0,12361.0,287,1,1,1,1.899000e+02,1,111,1.0,Belgium,Lost
0,12362.0,3,5,13,5,5.154580e+03,5,555,5.0,Belgium,champion
0,12362.0,3,5,13,5,5.154580e+03,5,555,5.0,Belgium,loyal customer
0,12363.0,110,3,2,2,5.520000e+02,3,323,2.5,Unspecified,Potential Loyalist
...,...,...,...,...,...,...,...,...,...,...,...
0,18259.0,25,5,3,3,2.338600e+03,5,535,4.0,United Kingdom,loyal customer
0,18260.0,173,2,8,5,2.595000e+03,5,255,5.0,United Kingdom,loyal customer
0,18260.0,173,2,8,5,2.595000e+03,5,255,5.0,United Kingdom,At Risk
0,18261.0,43,4,2,2,3.242400e+02,2,422,2.0,United Kingdom,Potential Loyalist
0,18262.0,140,3,1,1,1.494800e+02,1,311,1.0,United Kingdom,Potential Loyalist
0,18262.0,140,3,1,1,1.494800e+02,1,311,1.0,United Kingdom,Promising
0,18262.0,140,3,1,1,1.494800e+02,1,311,1.0,United Kingdom,About To Sleep
0,18263.0,23,5,4,3,1.211080e+03,4,534,3.5,United Kingdom,loyal customer
0,18265.0,72,4,2,2,8.015100e+02,3,423,2.5,United Kingdom,Potential Loyalist
0,18269.0,358,1,2,2,1.389000e+02,1,121,1.5,United Kingdom,Hibernating
0,18269.0,358,1,2,2,1.389000e+02,1,121,1.5,United Kingdom,Lost
0,18270.0,38,4,3,3,2.389500e+02,1,431,2.0,United Kingdom,Potential Loyalist
0,18272.0,3,5,7,4,3.064780e+03,5,545,4.5,United Kingdom,champion
0,18272.0,3,5,7,4,3.064780e+03,5,545,4.5,United Kingdom,loyal customer
0,18273.0,2,5,3,3,2.040000e+02,1,531,2.0,United Kingdom,Potential Loyalist
0,18274.0,18,5,2,2,1.243450e-14,1,521,1.5,United Kingdom,Potential Loyalist
0,18276.0,21,5,3,3,3.233600e+02,2,532,2.5,United Kingdom,Potential Loyalist
0,18277.0,58,4,2,2,9.763000e+01,1,421,1.5,United Kingdom,Potential Loyalist
0,18278.0,74,4,1,1,1.739000e+02,1,411,1.0,United Kingdom,Potential Loyalist
0,18278.0,74,4,1,1,1.739000e+02,1,411,1.0,United Kingdom,Recent Customers
0,18278.0,74,4,1,1,1.739000e+02,1,411,1.0,United Kingdom,Promising
0,18280.0,278,1,1,1,1.806000e+02,1,111,1.0,United Kingdom,Hibernating
0,18280.0,278,1,1,1,1.806000e+02,1,111,1.0,United Kingdom,Lost
0,18281.0,181,2,1,1,8.082000e+01,1,211,1.0,United Kingdom,About To Sleep
0,18281.0,181,2,1,1,8.082000e+01,1,211,1.0,United Kingdom,Hibernating
0,18281.0,181,2,1,1,8.082000e+01,1,211,1.0,United Kingdom,Lost
0,18282.0,8,5,3,3,1.766000e+02,1,531,2.0,United Kingdom,Potential Loyalist
0,18283.0,4,5,16,5,2.094880e+03,5,555,5.0,United Kingdom,champion
0,18283.0,4,5,16,5,2.094880e+03,5,555,5.0,United Kingdom,loyal customer
0,18287.0,43,4,3,3,1.837280e+03,4,434,3.5,United Kingdom,loyal customer

In [65]:
# data visualization in tableau

newrfm.to_csv(R"D:\rfm analysis\rmf analysis.csv",header=True,index=False)

In [72]:
newrfm['segmentation'].value_counts()

loyal customer                 2102
Potential Loyalist             1668
champion                       1233
Lost                            749
Hibernating                     749
At Risk                         452
About To Sleep                  335
Recent Customers                279
Customers Needing Attention     278
Promising                       212
Can’t Lose Them                  13
Name: segmentation, dtype: int64